package compliancexport

import (
	"bytes"
	"strings"
	"testing"
)

func TestRenderMarkdown_StartsWithH1(t *testing.T) {
	var buf bytes.Buffer
	if err := renderMarkdown(&buf, testExport()); err != nil {
		t.Fatal(err)
	}
	out := buf.String()

	if !strings.HasPrefix(out, "# HIPAA Security Rule") {
		t.Errorf("expected H1 header, got: %s", out[:min(len(out), 50)])
	}
}

func TestRenderMarkdown_ContainsTableDelimiters(t *testing.T) {
	var buf bytes.Buffer
	if err := renderMarkdown(&buf, testExport()); err != nil {
		t.Fatal(err)
	}
	out := buf.String()

	if !strings.Contains(out, "|---|") {
		t.Error("missing markdown table delimiters")
	}
}

func TestRenderMarkdown_GapSection(t *testing.T) {
	var buf bytes.Buffer
	if err := renderMarkdown(&buf, testExport()); err != nil {
		t.Fatal(err)
	}
	out := buf.String()

	if !strings.Contains(out, "## Gaps") {
		t.Error("missing gaps section")
	}
	if !strings.Contains(out, "CTL.B") {
		t.Error("missing gap control ID")
	}
	if !strings.Contains(out, "Bucket not encrypted") {
		t.Error("missing gap message")
	}
}

func TestRenderMarkdown_FooterPresent(t *testing.T) {
	var buf bytes.Buffer
	if err := renderMarkdown(&buf, testExport()); err != nil {
		t.Fatal(err)
	}
	out := buf.String()

	if !strings.Contains(out, "Generated by Stave") {
		t.Error("missing footer")
	}
	if !strings.Contains(out, "without cloud credentials") {
		t.Error("missing air-gap provenance note")
	}
}

func TestRenderMarkdown_NoANSI(t *testing.T) {
	var buf bytes.Buffer
	if err := renderMarkdown(&buf, testExport()); err != nil {
		t.Fatal(err)
	}
	out := buf.String()

	if strings.Contains(out, "\033[") {
		t.Error("markdown output should not contain ANSI escape codes")
	}
}
