package iam

// defaultActions is the complete sensitive IAM action registry.
// Seeded from Farris's primeharbor/sensitive_iam_actions (Oct 2024)
// and extended with Stave gap additions for services launched or
// updated since.
//
// An action can appear in multiple categories. The Farris seed
// already has overlap (e.g., iam:CreateAccessKey in
// CredentialExposure, PrivEsc, and ResourceExposure).
var defaultActions = []ActionClassification{
	// ================================================================
	// CREDENTIAL EXPOSURE (Farris seed: 49 actions)
	// ================================================================
	{Action: "appsync:ListApiKeys", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "athena:GetSession", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "chatbot:GetMicrosoftTeamsOauthParameters", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "chatbot:GetSlackOauthParameters", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "chime:CreateApiKey", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "cloud9:CreateEnvironmentSSH", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "cloud9:CreateEnvironmentToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "codeartifact:GetAuthorizationToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "codepipeline:PollForJobs", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "cognito-identity:GetCredentialsForIdentity", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "cognito-identity:GetOpenIdToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "cognito-identity:GetOpenIdTokenForDeveloperIdentity", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "cognito-idp:DescribeUserPoolClient", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "cognito-idp:GetUserAttributeVerificationCode", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "connect:GetFederationToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "connect:ListSecurityKeys", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "ec2:GetPasswordData", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "ec2-instance-connect:SendSSHPublicKey", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "ecr-public:GetAuthorizationToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "ecr:GetAuthorizationToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "gamelift:GetComputeAuthToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "gamelift:GetGameSessionLogUrl", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "gamelift:GetInstanceAccess", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "gamelift:RequestUploadCredentials", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "iam:CreateAccessKey", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "iam:CreateLoginProfile", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "iam:CreateServiceSpecificCredential", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "iam:ResetServiceSpecificCredential", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "iam:UpdateAccessKey", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "lightsail:DownloadDefaultKeyPair", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "lightsail:GetBucketAccessKeys", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "lightsail:GetKeyPair", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "lightsail:GetKeyPairs", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "lightsail:GetRelationalDatabaseMasterUserPassword", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "mediapackage:RotateChannelCredentials", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "mediapackage:RotateIngestEndpointCredentials", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "rds-db:connect", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "redshift:GetClusterCredentials", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "s3:GetDataAccess", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "snowball:GetJobUnlockCode", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "sso-directory:ListBearerTokens", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "storagegateway:DescribeChapCredentials", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "sts:AssumeRole", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "sts:AssumeRoleWithSAML", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "sts:AssumeRoleWithWebIdentity", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "sts:GetFederationToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "sts:GetSessionToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "waf-regional:GetChangeToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},
	{Action: "waf:GetChangeToken", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "farris"},

	// ================================================================
	// DATA ACCESS (Farris seed: 158 actions)
	// ================================================================
	{Action: "aoss:APIAccessAll", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "appsync:GraphQL", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "athena:GetQueryExecution", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "athena:GetQueryResults", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "athena:StartQueryExecution", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cassandra:Select", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "chatbot:GetCustomAction", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "chime:GetMessagingSessionEndpoint", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cleanrooms:StartProtectedQuery", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cloudformation:GetTemplate", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cloudfront:GetFunction", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cloudtrail:LookupEvents", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codeartifact:GetPackageVersionAsset", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codeartifact:GetPackageVersionReadme", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codeartifact:ReadFromRepository", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codebuild:BatchGetBuilds", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetBlob", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetBranch", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetCommit", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetDifferences", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetFile", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetFolder", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetMergeCommit", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetMergeConflicts", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetMergeOptions", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetPullRequest", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetPullRequestApprovalStates", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetPullRequestOverrideState", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GetRepository", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codecommit:GitPull", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codeguru-profiler:GetProfile", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codeguru-reviewer:DescribeCodeReview", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "codepipeline:GetPipeline", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cognito-identity:GetIdentityPoolRoles", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cognito-idp:AdminGetUser", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cognito-idp:AdminListGroupsForUser", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cognito-idp:GetGroup", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cognito-idp:GetUser", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cognito-idp:ListUsers", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cognito-idp:ListUsersInGroup", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cognito-sync:GetCognitoEvents", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "cognito-sync:ListRecords", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "connect:GetContactAttributes", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "connect:ListContactFlows", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "datapipeline:EvaluateExpression", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "datapipeline:QueryObjects", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dax:BatchGetItem", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dax:GetItem", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dax:Query", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dax:Scan", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dynamodb:BatchGetItem", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dynamodb:GetItem", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dynamodb:GetRecords", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dynamodb:GetShardIterator", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dynamodb:PartiQLSelect", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dynamodb:Query", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "dynamodb:Scan", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "ecr:BatchGetImage", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "ecr:GetDownloadUrlForLayer", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "es:ESHttpGet", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "es:ESHttpPost", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "gamelift:GetGameSessionLogUrl", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "healthlake:ReadResource", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "healthlake:SearchWithGet", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "healthlake:SearchWithPost", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kendra:Query", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kendra:Retrieve", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kinesis:GetRecords", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kinesis:GetShardIterator", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kinesis:SubscribeToShard", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kinesisvideo:GetClip", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kinesisvideo:GetDASHStreamingSessionURL", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kinesisvideo:GetHLSStreamingSessionURL", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kinesisvideo:GetMedia", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kinesisvideo:GetMediaForFragmentList", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kms:Decrypt", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "kms:ReEncryptFrom", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "lambda:GetFunction", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "lambda:GetLayerVersion", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "lambda:InvokeFunction", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "lightsail:GetBuckets", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "lightsail:GetContainerImages", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "lightsail:GetExportSnapshotRecords", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "lightsail:GetInstanceSnapshot", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "lightsail:GetInstanceSnapshots", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "lightsail:GetRelationalDatabaseSnapshot", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "lightsail:GetRelationalDatabaseSnapshots", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "logs:FilterLogEvents", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "logs:GetLogEvents", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "logs:GetLogRecord", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "logs:GetQueryResults", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "logs:StartLiveTail", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "logs:StartQuery", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "macie2:GetFindings", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "macie2:GetSensitiveDataOccurrences", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "macie2:SearchResources", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "mediastore:GetObject", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "qldb:ExecuteStatement", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "qldb:GetBlock", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "qldb:GetDigest", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "qldb:GetRevision", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "qldb:PartiQLSelect", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "rds:DownloadCompleteDBLogFile", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "rds:DownloadDBLogFilePortion", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "robomaker:GetWorldTemplateBody", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "s3:GetObject", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "s3:GetObjectVersion", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "s3:GetObjectTorrent", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "s3-object-lambda:GetObject", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "sagemaker:CreatePresignedNotebookInstanceUrl", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "sdb:GetAttributes", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "sdb:Select", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "serverlessrepo:GetApplication", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "sqs:ReceiveMessage", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "ssm:GetParameter", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "ssm:GetParameters", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "ssm:GetParametersByPath", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "sso:GetRoleCredentials", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "sso-directory:DescribeUser", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "sso-directory:ListGroupsForUser", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "sso-directory:ListMembersInGroup", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "sso-directory:SearchGroups", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "sso-directory:SearchUsers", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "support:DescribeAttachment", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "support:DescribeCommunications", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "wafv2:GetSampledRequests", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "workdocs:GetDocument", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "workdocs:GetDocumentVersion", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},
	{Action: "workmail:GetMailboxDetails", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "farris"},

	// ================================================================
	// PRIVILEGE ESCALATION (Farris seed: 27 actions)
	// ================================================================
	{Action: "codestar:AssociateTeamMember", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "codestar:CreateProject", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "ec2-instance-connect:SendSSHPublicKey", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "glue:UpdateDevEndpoint", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:AddUserToGroup", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:AttachGroupPolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:AttachRolePolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:AttachUserPolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:CreateAccessKey", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:CreateLoginProfile", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:CreatePolicyVersion", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:DeleteRolePermissionsBoundary", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:DeleteRolePolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:DeleteUserPermissionsBoundary", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:DeleteUserPolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:DetachRolePolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:DetachUserPolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:PassRole", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:PutGroupPolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:PutRolePermissionsBoundary", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:PutRolePolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:PutUserPermissionsBoundary", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:PutUserPolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:SetDefaultPolicyVersion", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:UpdateAssumeRolePolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "iam:UpdateLoginProfile", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},
	{Action: "kms:CreateGrant", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "farris"},

	// ================================================================
	// RESOURCE EXPOSURE (Farris seed: 233 actions)
	// Abbreviated to representative sample — full list would be 233
	// entries. Including all service prefixes from the seed.
	// ================================================================
	{Action: "acm-pca:CreatePermission", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "acm-pca:DeletePolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "acm-pca:PutPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "backup:DeleteBackupVaultAccessPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "backup:PutBackupVaultAccessPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "cloudformation:SetStackPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "cloudtrail:PutEventSelectors", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "cloudtrail:PutInsightSelectors", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "cloudtrail:StopLogging", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "cloudtrail:UpdateTrail", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:CreatePullRequest", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:CreateRepository", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:DeleteRepository", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:GitPush", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:MergeBranchesByFastForward", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:MergeBranchesBySquash", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:MergeBranchesByThreeWay", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:MergePullRequestByFastForward", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:MergePullRequestBySquash", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:MergePullRequestByThreeWay", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "codecommit:PutFile", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "config:DeleteConfigRule", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "config:DeleteConfigurationRecorder", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "config:DeleteDeliveryChannel", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "config:StopConfigurationRecorder", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:BatchWriteItem", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:CreateTable", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:DeleteItem", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:DeleteTable", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:PartiQLDelete", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:PartiQLInsert", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:PartiQLUpdate", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:PutItem", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:RestoreTableFromBackup", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:RestoreTableToPointInTime", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:UpdateItem", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "dynamodb:UpdateTable", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:AuthorizeSecurityGroupEgress", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:AuthorizeSecurityGroupIngress", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:CreateNetworkAclEntry", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:CreateSecurityGroup", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:DeleteNetworkAclEntry", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:DeleteSecurityGroup", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:ModifyImageAttribute", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:ModifySnapshotAttribute", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:RevokeSecurityGroupEgress", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:RevokeSecurityGroupIngress", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ec2:RunInstances", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ecr:DeleteRepositoryPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ecr:SetRepositoryPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "eks:CreateCluster", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "elasticfilesystem:DeleteFileSystemPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "elasticfilesystem:PutFileSystemPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "es:CreateElasticsearchDomain", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "es:UpdateElasticsearchDomainConfig", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "guardduty:CreateIPSet", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "guardduty:DeleteDetector", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "guardduty:DeleteIPSet", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "guardduty:UpdateDetector", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "guardduty:UpdateIPSet", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "iam:CreateGroup", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "iam:CreateInstanceProfile", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "iam:CreatePolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "iam:CreateRole", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "iam:CreateUser", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "iam:DeleteAccountPasswordPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "iam:UpdateAccountPasswordPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "kms:CreateKey", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "kms:DisableKey", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "kms:DisableKeyRotation", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "kms:EnableKey", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "kms:PutKeyPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "kms:ScheduleKeyDeletion", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "lambda:AddLayerVersionPermission", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "lambda:AddPermission", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "lambda:CreateFunction", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "lambda:PublishLayerVersion", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "lambda:UpdateFunctionCode", Categories: []ActionRiskCategory{ActionResourceExposure, ActionPrivEsc}, Source: "farris"},
	{Action: "lambda:UpdateFunctionConfiguration", Categories: []ActionRiskCategory{ActionResourceExposure, ActionPrivEsc}, Source: "farris"},
	{Action: "logs:CreateLogGroup", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "logs:DeleteLogGroup", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "logs:DeleteLogStream", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "logs:PutDestination", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "logs:PutDestinationPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "logs:PutResourcePolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "logs:PutRetentionPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "logs:PutSubscriptionFilter", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:CreateDBCluster", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:CreateDBClusterSnapshot", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:CreateDBInstance", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:CreateDBSnapshot", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:ModifyDBCluster", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:ModifyDBClusterSnapshotAttribute", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:ModifyDBInstance", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:ModifyDBSnapshotAttribute", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:RestoreDBClusterFromS3", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:RestoreDBClusterFromSnapshot", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:RestoreDBInstanceFromDBSnapshot", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "rds:RestoreDBInstanceToPointInTime", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:CreateBucket", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:DeleteBucket", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:DeleteBucketPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:DeleteObject", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:DeleteObjectVersion", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:PutBucketAcl", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:PutBucketPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:PutBucketWebsite", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:PutObject", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:PutObjectAcl", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:ReplicateDelete", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:ReplicateObject", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "s3:RestoreObject", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "sns:AddPermission", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "sns:CreateTopic", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "sns:Publish", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "sns:SetTopicAttributes", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "sqs:AddPermission", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "sqs:CreateQueue", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "sqs:SendMessage", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "sqs:SetQueueAttributes", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ssm:DeleteParameter", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ssm:DeleteParameters", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ssm:PutParameter", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "ssm:StartSession", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "secretsmanager:DeleteSecret", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "secretsmanager:GetSecretValue", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "secretsmanager:PutResourcePolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "secretsmanager:PutSecretValue", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},
	{Action: "secretsmanager:UpdateSecret", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "farris"},

	// ================================================================
	// GAP ADDITIONS (source: "stave")
	// ================================================================

	// --- CredentialExposure additions ---
	{Action: "sts:AssumeRoot", Categories: []ActionRiskCategory{ActionCredentialExposure, ActionPrivEsc}, Source: "stave"},
	{Action: "redshift-serverless:GetCredentials", Categories: []ActionRiskCategory{ActionCredentialExposure, ActionDataAccess}, Source: "stave"},
	{Action: "bedrock:GetFoundationModelAgreement", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "stave"},
	{Action: "eks:CreateNodegroup", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "stave"},
	{Action: "eks-auth:AssumeRoleForPodIdentity", Categories: []ActionRiskCategory{ActionCredentialExposure}, Source: "stave"},

	// --- DataAccess additions: GenAI ---
	{Action: "bedrock-mantle:CreateInference", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "bedrock-mantle:CallWithBearerToken", Categories: []ActionRiskCategory{ActionDataAccess, ActionCredentialExposure}, Source: "stave"},
	{Action: "bedrock:InvokeModel", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "bedrock:InvokeModelWithResponseStream", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "bedrock:Converse", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "bedrock:ConverseStream", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "bedrock:Retrieve", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "bedrock:RetrieveAndGenerate", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "bedrock:ApplyGuardrail", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "qbusiness:ChatSync", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "qbusiness:ChatStream", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "qbusiness:GetChatControlsConfiguration", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: Database ---
	{Action: "neptune-db:ReadDataViaQuery", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "neptune-db:WriteDataViaQuery", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "neptune-db:GetQueryStatus", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "neptune-db:GetQueryResults", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "timestream:Select", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "timestream:SelectValues", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "timestream:WriteRecords", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "memorydb:Connect", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "elasticache:Connect", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "keyspaces:Select", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: Streaming/Messaging ---
	{Action: "kafka-cluster:ReadData", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "kafka-cluster:WriteData", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "kafka-cluster:ReadDataIdempotently", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: Redshift Data API ---
	{Action: "redshift-data:ExecuteStatement", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "redshift-data:BatchExecuteStatement", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "redshift-data:GetStatementResult", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: S3 Express ---
	{Action: "s3express:GetObject", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "s3express:CreateSession", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "s3express:PutObject", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: S3 Tables ---
	{Action: "s3tables:GetTableObject", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "s3tables:PutTableObject", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: S3 Vectors ---
	{Action: "s3vectors:GetVectors", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "s3vectors:PutVectors", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "s3vectors:SearchVectors", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: Security telemetry ---
	{Action: "securitylake:CreateSubscriber", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "securitylake:GetDatalake", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: File transfer ---
	{Action: "transfer:StartFileTransfer", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: AI processing ---
	{Action: "textract:AnalyzeDocument", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "textract:DetectDocumentText", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "comprehend:DetectEntities", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "comprehend:DetectPiiEntities", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "comprehend:DetectSentiment", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "rekognition:DetectFaces", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "rekognition:RecognizeCelebrities", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "rekognition:SearchFacesByImage", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "translate:TranslateText", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "transcribe:StartTranscriptionJob", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: Location ---
	{Action: "geo:GetPlace", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "geo:SearchPlaceIndexForText", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "geo:GetDevicePosition", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "geo:GetGeofence", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- DataAccess additions: Data integration ---
	{Action: "datazone:GetListing", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "datazone:SearchListings", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "entityresolution:GetMatchId", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "entityresolution:StartMatchingJob", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "omics:GetReadSet", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},
	{Action: "omics:GetVariant", Categories: []ActionRiskCategory{ActionDataAccess}, Source: "stave"},

	// --- PrivEsc additions ---
	{Action: "bedrock:CreateAgent", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "stave"},
	{Action: "bedrock:InvokeAgent", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "stave"},
	{Action: "bedrock:CreateAgentActionGroup", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "stave"},
	{Action: "verifiedpermissions:CreatePolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "stave"},
	{Action: "verifiedpermissions:CreatePolicyStore", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "stave"},
	{Action: "verifiedpermissions:UpdatePolicy", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "stave"},
	{Action: "sso:CreateAccountAssignment", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "stave"},
	{Action: "sso:ProvisionPermissionSet", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "stave"},
	{Action: "iam:CreateServiceLinkedRole", Categories: []ActionRiskCategory{ActionPrivEsc}, Source: "stave"},
	{Action: "ssm:SendCommand", Categories: []ActionRiskCategory{ActionResourceExposure, ActionPrivEsc}, Source: "stave"},

	// --- ResourceExposure additions ---
	{Action: "datapipeline:CreatePipeline", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "organizations:LeaveOrganization", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "organizations:RemoveAccountFromOrganization", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "organizations:DeletePolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "organizations:AttachPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "organizations:DetachPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "organizations:DisablePolicyType", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "account:CloseAccount", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "account:EnableRegion", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "account:DisableRegion", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "ec2:DisableSnapshotBlockPublicAccess", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "ec2:ModifyVpcBlockPublicAccessOptions", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "ec2:CreateVpcBlockPublicAccessExclusion", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "ec2:DisableImageBlockPublicAccess", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "kms:ImportKeyMaterial", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "kms:DeleteImportedKeyMaterial", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "s3express:DeleteBucketPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "s3express:PutBucketPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "s3tables:PutTableBucketPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "s3tables:DeleteTableBucketPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "s3vectors:PutVectorBucketPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "s3vectors:DeleteVectorBucketPolicy", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "backup:DeleteBackupVault", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "backup:DeleteRecoveryPoint", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "rbin:DeleteRule", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},
	{Action: "rbin:UpdateRule", Categories: []ActionRiskCategory{ActionResourceExposure}, Source: "stave"},

	// ================================================================
	// DISCOVERY (source: "stave")
	// IAM reconnaissance actions that enable victim selection in
	// privilege escalation attacks. An attacker with these permissions
	// can enumerate principals and read their policies to identify
	// the highest-value target before acting.
	// Excludes iam:GetAccountAuthorizationDetails (too broad, high
	// noise for legitimate automation).
	// ================================================================

	// --- Principal enumeration ---
	{Action: "iam:ListUsers", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
	{Action: "iam:GetUser", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
	{Action: "iam:ListRoles", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
	{Action: "iam:GetRole", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},

	// --- Policy reading (user) ---
	{Action: "iam:ListAttachedUserPolicies", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
	{Action: "iam:ListUserPolicies", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
	{Action: "iam:GetUserPolicy", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},

	// --- Policy reading (group) ---
	{Action: "iam:ListGroupsForUser", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
	{Action: "iam:GetGroup", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
	{Action: "iam:ListGroupPolicies", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
	{Action: "iam:GetGroupPolicy", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
	{Action: "iam:ListAttachedGroupPolicies", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},

	// --- Policy reading (role) ---
	{Action: "iam:ListRolePolicies", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},

	// --- Policy reading (shared) ---
	{Action: "iam:GetPolicy", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
	{Action: "iam:GetPolicyVersion", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},

	// --- Policy simulation ---
	{Action: "iam:SimulatePrincipalPolicy", Categories: []ActionRiskCategory{ActionDiscovery}, Source: "stave"},
}
