#!/usr/bin/env python3
"""Generate AWS CLI commands from Stave structured remediation JSON.

Usage:
    stave rank --in output.json --format json | python3 to-aws-cli.py > fix.sh
"""
import json, sys

data = json.load(sys.stdin)
entries = data.get("entries", [])

print("#!/bin/bash")
print("# Generated by Stave structured remediation output")
print("set -euo pipefail")
print()

for entry in entries:
    changes = entry.get("remediation", {}).get("changes", [])
    if not changes:
        continue

    asset_id = entry.get("asset_id", "unknown")
    print(f"# {entry.get('control_id', '')} on {asset_id}")

    for change in changes:
        path = change.get("property_path", "")
        safe = change.get("has_safe_default", False)

        if not safe:
            print(f"# TODO: {change.get('description', path)} (context-dependent)")
            continue

        # S3 public access block
        if "public_access_block" in path and "s3" in asset_id.lower():
            bucket = asset_id.split(":::")[-1] if ":::" in asset_id else asset_id
            print(f"aws s3api put-public-access-block \\")
            print(f"  --bucket {bucket} \\")
            print(f"  --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true")

        # Generic: emit as comment
        else:
            print(f"# {change.get('description', path)}")
            print(f"# Property: {path} = {change.get('required_value', '?')}")

    print()
