package upcoming

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/sufield/stave/internal/cli/ui"
	"github.com/sufield/stave/internal/pkg/timeutil"
)

func buildUpcomingOutput(opts upcomingRunOptions, summary upcomingSummary, items []upcomingItem) upcomingOutput {
	return upcomingOutput{
		GeneratedAt:  opts.Now,
		ControlsDir:  opts.ControlsDir,
		Observations: opts.ObservationsDir,
		MaxUnsafe:    opts.MaxUnsafeRaw,
		DueSoon:      opts.DueSoonRaw,
		Summary:      summary,
		Items:        items,
	}
}

func writeUpcomingOutput(format ui.OutputFormat, w io.Writer, report string, jsonOut upcomingOutput) error {
	if format.IsJSON() {
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		if err := enc.Encode(jsonOut); err != nil {
			return fmt.Errorf("write report: %w", err)
		}
		return nil
	}
	if _, err := io.WriteString(w, report); err != nil {
		return fmt.Errorf("write report: %w", err)
	}
	return nil
}

func renderUpcomingSummaryMarkdown(summary upcomingSummary, dueSoonThreshold time.Duration) string {
	var b strings.Builder
	b.WriteString("## Snapshot SLA Summary\n\n")
	fmt.Fprintf(&b, "- Overdue: **%d**\n", summary.Overdue)
	fmt.Fprintf(&b, "- Due now: **%d**\n", summary.DueNow)
	fmt.Fprintf(&b, "- Due soon (<= %s): **%d**\n", timeutil.FormatDurationHuman(dueSoonThreshold), summary.DueSoon)
	fmt.Fprintf(&b, "- Later: **%d**\n", summary.Later)
	fmt.Fprintf(&b, "- Total action items: **%d**\n", summary.Total)
	return b.String()
}

func renderUpcomingMarkdown(items []upcomingItem, summary upcomingSummary, opts UpcomingRenderOptions) string {
	var b strings.Builder
	b.WriteString("# Upcoming Snapshot Action Items\n\n")
	b.WriteString("> Auto-generated by `stave upcoming`. Do not edit manually; regenerate after each new snapshot capture.\n\n")
	fmt.Fprintf(&b, "Generated at: `%s`\n\n", opts.Now.UTC().Format(time.RFC3339))
	b.WriteString(renderUpcomingSummaryMarkdown(summary, opts.DueSoonThreshold))
	b.WriteString("\n")

	if len(items) == 0 {
		b.WriteString("No upcoming snapshot action items.\n")
		return b.String()
	}

	b.WriteString("| Due At (UTC) | Status | Control | Asset | Type | First Unsafe | Last Seen Unsafe | Threshold | Time To Due |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, item := range items {
		fmt.Fprintf(&b,
			"| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n",
			item.DueAt.Format(time.RFC3339),
			item.Status,
			item.ControlID,
			item.AssetID,
			item.AssetType,
			item.FirstUnsafeAt.Format(time.RFC3339),
			item.LastSeenUnsafe.Format(time.RFC3339),
			timeutil.FormatDuration(item.Threshold),
			formatRemaining(item.Remaining),
		)
	}
	return b.String()
}

func formatRemaining(d time.Duration) string {
	switch {
	case d == 0:
		return "0h"
	case d < 0:
		return "-" + timeutil.FormatDurationHuman(-d)
	default:
		return timeutil.FormatDurationHuman(d)
	}
}
