package compliance

import (
	"fmt"
	"io"
)

func renderMarkdown(w io.Writer, export *EvidenceExport) error { //nolint:unparam // error return for format-dispatch interface consistency
	// Header
	fmt.Fprintf(w, "# %s — Compliance Evidence Package\n\n", export.Profile.Name)
	fmt.Fprintf(w, "**Snapshot:** %s\n", export.SnapshotID)
	fmt.Fprintf(w, "**Assessed:** %s\n", export.ExportedAt.Format("2006-01-02 15:04 UTC"))
	fmt.Fprintf(w, "**Stave version:** %s\n\n", export.StaveVersion)

	// Overall posture
	fmt.Fprintln(w, "## Overall Posture")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Category | Met | Total | Coverage |")
	fmt.Fprintln(w, "|---|---|---|---|")
	fmt.Fprintf(w, "| **Overall** | **%d** | **%d** | **%.1f%%** |\n\n",
		export.Score.RequirementsMet, export.Score.RequirementsTotal, export.Score.OverallPercent)

	// Requirements summary
	fmt.Fprintln(w, "## Requirements Summary")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Requirement | Description | Status | Controls |")
	fmt.Fprintln(w, "|---|---|---|---|")

	for i := range export.Requirements {
		r := &export.Requirements[i]
		icon := mdStatusIcon(r.Status)
		ctlSummary := controlCountSummary(r.Controls)
		desc := truncate(r.Description, 40)
		fmt.Fprintf(w, "| %s | %s | %s | %s |\n", r.ID, desc, icon, ctlSummary)
	}
	fmt.Fprintln(w)

	// Gaps
	hasGaps := false
	for i := range export.Requirements {
		if len(export.Requirements[i].Gaps) > 0 {
			hasGaps = true
			break
		}
	}

	if hasGaps {
		fmt.Fprintln(w, "## Gaps")
		fmt.Fprintln(w)

		for i := range export.Requirements {
			r := &export.Requirements[i]
			if len(r.Gaps) == 0 {
				continue
			}
			fmt.Fprintf(w, "### %s — %s (%s)\n\n", r.ID, r.Description, statusLabel(r.Status))
			fmt.Fprintf(w, "**%d gap(s) found**\n\n", len(r.Gaps))
			fmt.Fprintln(w, "| Control | Resource | Severity | Message |")
			fmt.Fprintln(w, "|---|---|---|---|")
			for j := range r.Gaps {
				g := &r.Gaps[j]
				arn := truncate(g.ResourceARN, 60)
				fmt.Fprintf(w, "| %s | %s | %s | %s |\n", g.ControlID, arn, g.Severity, g.Message)
			}
			fmt.Fprintln(w)
		}
	}

	// Footer
	fmt.Fprintln(w, "---")
	fmt.Fprintf(w, "*Generated by Stave %s. Evidence produced from local snapshot without cloud credentials.*\n", export.StaveVersion)

	return nil
}

func mdStatusIcon(status string) string {
	switch status {
	case "met":
		return "SATISFIED"
	case "not_met":
		return "NOT MET"
	case "not_evaluated":
		return "NOT EVAL"
	case "incomplete":
		return "INCOMPLETE"
	default:
		return status
	}
}
