package export

import (
	"fmt"
	"strconv"
	"strings"

	policy "github.com/sufield/stave/internal/core/controldef"
	"github.com/sufield/stave/internal/core/predicate"
)

// GenerateRego translates a slice of Stave controls to OPA Rego rules.
// Each control becomes one or more deny[msg] rules in the output.
func GenerateRego(controls []policy.ControlDefinition, pkg string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("# Auto-generated by: stave export --format rego\n")
	fmt.Fprintf(&b, "# Controls: %d\n\n", len(controls))

	for i := range controls {
		writeControl(&b, &controls[i])
	}

	return b.String()
}

func writeControl(b *strings.Builder, ctl *policy.ControlDefinition) {
	fmt.Fprintf(b, "# %s — %s\n", ctl.ID, ctl.Name)
	fmt.Fprintf(b, "# Severity: %s\n", ctl.Severity)

	if ctl.UnsafePredicateAlias != "" {
		fmt.Fprintf(b, "# Skipped: uses predicate alias %q\n\n", ctl.UnsafePredicateAlias)
		return
	}

	pred := ctl.UnsafePredicate
	if len(pred.All) == 0 && len(pred.Any) == 0 {
		b.WriteString("# Skipped: no unsafe_predicate defined\n\n")
		return
	}

	slug := controlSlug(string(ctl.ID))
	msg := string(ctl.ID) + ": " + ctl.Name

	if len(pred.All) > 0 {
		writeAllDeny(b, slug, msg, pred.All)
	} else {
		// Top-level any: each branch is an independent deny rule.
		for i := range pred.Any {
			rule := &pred.Any[i]
			if rule.Field.IsZero() && len(rule.All) > 0 {
				writeAllDeny(b, slug+"_branch_"+strconv.Itoa(i), msg, rule.All)
			} else if !rule.Field.IsZero() {
				b.WriteString("deny[msg] {\n")
				writeCondition(b, rule, "    ")
				fmt.Fprintf(b, "    msg := %q\n", msg)
				b.WriteString("}\n")
			}
		}
	}
	b.WriteString("\n")
}

func writeAllDeny(b *strings.Builder, slug, msg string, rules []policy.PredicateRule) {
	// Collect simple conditions and nested any blocks.
	var simpleIdxs []int
	var anyBlocks []struct {
		index int
		rules []policy.PredicateRule
	}

	for i := range rules {
		if rules[i].Field.IsZero() && len(rules[i].Any) > 0 {
			anyBlocks = append(anyBlocks, struct {
				index int
				rules []policy.PredicateRule
			}{i, rules[i].Any})
		} else {
			simpleIdxs = append(simpleIdxs, i)
		}
	}

	b.WriteString("deny[msg] {\n")
	for _, idx := range simpleIdxs {
		writeCondition(b, &rules[idx], "    ")
	}
	for _, ab := range anyBlocks {
		helperName := slug + "_any_" + strconv.Itoa(ab.index)
		fmt.Fprintf(b, "    %s\n", helperName)
	}
	fmt.Fprintf(b, "    msg := %q\n", msg)
	b.WriteString("}\n")

	// Write helper rules for any blocks.
	for _, ab := range anyBlocks {
		helperName := slug + "_any_" + strconv.Itoa(ab.index)
		for i := range ab.rules {
			b.WriteString(helperName + " { ")
			writeInlineCondition(b, &ab.rules[i])
			b.WriteString(" }\n")
		}
	}
}

func writeCondition(b *strings.Builder, r *policy.PredicateRule, indent string) {
	if r.Field.IsZero() {
		return
	}
	path := fieldToRego(r.Field)
	b.WriteString(indent)
	b.WriteString(conditionExpr(path, r.Op, r.Value))
	b.WriteString("\n")
}

func writeInlineCondition(b *strings.Builder, r *policy.PredicateRule) {
	if r.Field.IsZero() {
		return
	}
	path := fieldToRego(r.Field)
	b.WriteString(conditionExpr(path, r.Op, r.Value))
}

func conditionExpr(path string, op predicate.Operator, val policy.Operand) string {
	v := formatValue(val.Raw())

	switch op {
	case predicate.OpEq:
		return path + " == " + v
	case predicate.OpNe:
		return path + " != " + v
	case predicate.OpGt:
		return path + " > " + v
	case predicate.OpLt:
		return path + " < " + v
	case predicate.OpGte:
		return path + " >= " + v
	case predicate.OpLte:
		return path + " <= " + v
	case predicate.OpPresent:
		return path
	case predicate.OpMissing:
		return "not " + path
	case predicate.OpContains:
		return "contains(" + path + ", " + v + ")"
	case predicate.OpIn:
		return path + " == " + v + "[_]"
	default:
		return "# unsupported operator: " + path + " " + string(op) + " " + v
	}
}

func fieldToRego(f predicate.FieldPath) string {
	raw := f.String()
	// Strip "properties." prefix — Rego input maps directly.
	raw = strings.TrimPrefix(raw, "properties.")
	return "input." + raw
}

func formatValue(v any) string {
	switch val := v.(type) {
	case bool:
		if val {
			return "true"
		}
		return "false"
	case string:
		return strconv.Quote(val)
	case float64:
		if val == float64(int(val)) {
			return strconv.Itoa(int(val))
		}
		return strconv.FormatFloat(val, 'g', -1, 64)
	case []any:
		var elems []string
		for _, e := range val {
			elems = append(elems, formatValue(e))
		}
		return "[" + strings.Join(elems, ", ") + "]"
	default:
		return fmt.Sprintf("%v", v)
	}
}

func controlSlug(id string) string {
	s := strings.ToLower(id)
	s = strings.ReplaceAll(s, ".", "_")
	return s
}
