"""Render CATALOG.md + per-example multi-engine-results.md from
/tmp/h1_matrix.json."""
from __future__ import annotations

import json
import pathlib
import re
from collections import defaultdict

HERE = pathlib.Path(__file__).resolve().parent
STAVE = HERE.parent.parent
REPO = STAVE.parent
EXAMPLES = STAVE / "examples"
MATRIX_PATH = HERE / "matrix.json"

# Patterns that classify an example into a high-level attack family
# for the catalog index.
PATTERN_GROUPS = {
    "Anonymous Access via Identity Pools": [
        "cognito-self-register-to-aws-creds",
    ],
    "IAM Privilege Escalation": [
        "iam-21-privesc-5-patterns",
        "iam-overpermission-wildcard",
        "iam-attach-user-policy-self",
        "iam-autoscaling-privesc-bypass",
    ],
    "Cross-Service Trust Chains": [
        "iam-multi-hop-trust",
        "sns-secrets-compound-chain",
    ],
    "S3 Exposure & Tenant Boundaries": [
        "s3-public-read-policy",
        "s3-public-list-policy",
        "s3-broad-write-scope",
        "s3-tenant-prefix-isolation",
        "s3-bucket-name-dangling",
        "s3-cross-account-replication-overperm",
        "s3-dotgit-readable",
    ],
    "Cognito User Pools": [
        "cognito-no-mfa-advanced-security",
    ],
    "EKS / Kubernetes": [
        "eks-aws-auth-template-injection",
        "eks-rbac-webhook-config-access",
    ],
    "Defense Evasion": [
        "cloudtrail-stop-logging",
    ],
    "Network / API Boundaries": [
        "apigw-private-api-scoped-deny",
    ],
    "Lifecycle Drift": [
        "staging-stale-endpoint",
    ],
}


def short_engine_verdict(eng_name: str, cell: dict) -> str:
    """One-line summary of an engine's verdict for a fixture cell."""
    if cell is None:
        return "—"
    v = cell.get("verdict")
    if v == "n/a":
        return "n/a"
    if v == "skipped":
        return "skipped"
    if v == "error":
        return f"error ({cell.get('detail','?')[:40]})"

    if eng_name == "cel":
        n = cell.get("findings", 0)
        st = cell.get("verdict", "?")
        return f"{n} finding(s) ({st})"
    if eng_name == "souffle":
        rels = cell.get("rels", {})
        anon = rels.get("anonymous_reachable", 0)
        sreg = rels.get("self_register_reachable", 0)
        total = rels.get("reachable", 0)
        if total == 0:
            return "0 reachable"
        return f"{total} reach / {anon} anon / {sreg} self-reg"
    if eng_name == "clingo":
        kinds = cell.get("violations", [])
        if not kinds:
            return "no violations"
        return f"{len(kinds)} kind(s): {', '.join(kinds)}"
    if eng_name == "prolog":
        n = cell.get("proof_steps", 0)
        return f"{n} proof step(s)" if n else "no proof"
    if eng_name == "pysat":
        if v == "UNSAFE":
            cs = cell.get("compounds", [])
            return f"UNSAFE ({len(cs)} compound(s))" if cs else "UNSAFE"
        return v
    if eng_name == "risk":
        if cell.get("p_exploit_pct") is not None:
            return f"P={cell['p_exploit_pct']:.0f}% ({v})"
        return v
    if eng_name == "tla":
        d = cell.get("drift_margin")
        return f"{v}" + (f" (drift={d})" if d is not None else "")
    if eng_name == "game":
        return v
    return v or "—"


def smt_summary(smt_queries: list[dict]) -> str:
    if not smt_queries:
        return "—"
    parts = []
    for q in smt_queries:
        name = q["query"].split("/")[-1]
        z3v = q["z3"].get("verdict")
        parts.append(f"{name}: {z3v}")
    return "; ".join(parts)


def build_matrix(matrix: dict) -> dict[str, list[dict]]:
    by_example: dict[str, list[dict]] = defaultdict(list)
    for f in matrix["fixtures"]:
        by_example[f["example"]].append(f)
    return by_example


def render_per_example(example: str, fixtures: list[dict]) -> str:
    """Render multi-engine-results.md content for one example."""
    title = example.replace("-", " ").title()
    lines = [
        f"# {title} — Multi-Engine Analysis",
        "",
        "Auto-generated by the H1 fixture × engine matrix harness.",
        f"Source: `examples/{example}/fixtures/`. Engines invoked",
        "against each fixture's observation snapshots.",
        "",
        "## Engine verdicts per fixture",
        "",
    ]
    for fix in sorted(fixtures, key=lambda f: f["fixture"]):
        lines.append(f"### `{fix['fixture']}`")
        lines.append("")
        cel = fix["cel"]
        lines.append(f"- **CEL** — {short_engine_verdict('cel', cel)}")
        if cel.get("controls"):
            lines.append("  - controls fired: " +
                         ", ".join(f"`{c}`" for c in cel["controls"]))
        lines.append(f"- **SMT (Z3 / cvc5 / Yices)** — "
                     f"{smt_summary(fix.get('smt_queries', []))}")
        lines.append(f"- **Soufflé** — {short_engine_verdict('souffle', fix.get('souffle'))}")
        lines.append(f"- **Clingo** — {short_engine_verdict('clingo', fix.get('clingo'))}")
        lines.append(f"- **Prolog** — {short_engine_verdict('prolog', fix.get('prolog'))}")
        lines.append(f"- **PySAT** — {short_engine_verdict('pysat', fix.get('pysat'))}")
        lines.append(f"- **Risk model** — {short_engine_verdict('risk', fix.get('risk'))}")
        lines.append(f"- **TLA+** — {short_engine_verdict('tla', fix.get('tla'))}")
        lines.append(f"- **Game theory** — {short_engine_verdict('game', fix.get('game'))}")
        lines.append("")
        # Fact export sizes
        ej = fix.get("export_jsonl") or {}
        es = fix.get("export_smt2") or {}
        lines.append(f"- *fact export*: `jsonl` {ej.get('lines', 0)} lines / "
                     f"`smt2` {es.get('lines', 0)} lines")
        lines.append(f"- *runtime*: {fix.get('elapsed_s', 0)}s")
        lines.append("")

    lines += [
        "## Reading the matrix",
        "",
        "An empty / `n/a` / 0-count engine cell is not a bug. Each",
        "engine is designed for a specific question shape:",
        "",
        "- **CEL** flags individual control violations on the",
        "  observation. 0 findings can mean (a) the control",
        "  predicate intentionally does not fire on this fixture",
        "  shape (the example may surface the issue only via SMT),",
        "  or (b) the fixture is the remediated counterpart.",
        "- **SMT solvers** are paired with specific `query.smt2`",
        "  files. A `—` for SMT means no `query.smt2` is paired",
        "  with this example yet — adding a query is the natural",
        "  follow-up.",
        "- **Soufflé** computes the full reachability graph from",
        "  Stave's exported triples. 0 reachable rows means no",
        "  identity-pool or assume-role edges in the SIR projection.",
        "- **Clingo / Prolog / PySAT** run their built-in rule",
        "  programs against the JSONL facts. An empty result means",
        "  the rule program does not yet have constraints / proof",
        "  rules / compound checks for this fixture's predicate set.",
        "- **Risk / TLA+ / Game theory** use small Python models",
        "  hand-written for the cognito-style chain. They quantify",
        "  cleanly on Cognito + identity-pool fixtures and degrade",
        "  to neutral verdicts on fixtures with no chain shape.",
        "",
        "## Adapting to your environment",
        "",
        "1. Export your own observations covering the same asset",
        "   types as this example (run any of the existing extractor",
        "   scripts under the [`extractors/` companion repo](https://github.com/sufield/stave-extractor)).",
        f"2. Replace `examples/{example}/fixtures/<phase>/observations/`",
        "   with your own snapshots.",
        "3. Re-run the example's `run.sh` (or `bash run.sh` if it",
        "   exists). The engines that fired on the bundled fixture",
        "   will fire on yours under the same shape.",
        "4. To run all engines at once, point the comparison",
        "   harness at this fixture: ",
        "   `bash examples/compare-engines/run.sh`.",
        "",
        "## See also",
        "",
        f"- Example source: [`examples/{example}/`](.)",
        f"- Original write-up / article: see `examples/{example}/README.md`",
        "- Fact-export reference: [`reference/fact-export.md`](../../docs/controls/reference.md)",
        "- All scenarios: [`examples/CATALOG.md`](../CATALOG.md)",
    ]
    return "\n".join(lines) + "\n"


def render_catalog(matrix: dict, by_example: dict[str, list[dict]]) -> str:
    lines = [
        "# Stave Examples Catalog",
        "",
        f"**{len(matrix['fixtures'])} fixture pairs** across",
        f"**{len(by_example)} example scenarios**, each tested",
        "against every available reasoning engine.",
        "",
        "Every scenario ships a vulnerable fixture and a remediated",
        "fixture. The matrix below shows what each engine reveals.",
        "Pick the scenario closest to your environment and adapt it.",
        "",
        "## By Attack Pattern",
        "",
    ]
    classified = set()
    for group_name, dirs in PATTERN_GROUPS.items():
        present = [d for d in dirs if d in by_example]
        if not present:
            continue
        lines.append(f"### {group_name}")
        lines.append("")
        for d in present:
            classified.add(d)
            fxs = by_example[d]
            phases = sorted(set(f["fixture"] for f in fxs))
            cel_summary = describe_example_cel(by_example[d])
            lines.append(
                f"- **[{d}]({d}/multi-engine-results.md)** — "
                f"{len(fxs)} fixture(s): {', '.join(phases)}. {cel_summary}"
            )
        lines.append("")
    other = sorted(set(by_example) - classified)
    if other:
        lines.append("### Other")
        lines.append("")
        for d in other:
            fxs = by_example[d]
            phases = sorted(set(f["fixture"] for f in fxs))
            lines.append(
                f"- **[{d}]({d}/multi-engine-results.md)** — "
                f"{len(fxs)} fixture(s): {', '.join(phases)}."
            )
        lines.append("")

    lines += [
        "## By Engine — \"I want to …\"",
        "",
        "| Question | Engine | How |",
        "|---|---|---|",
        "| Detect per-control violations on a snapshot | **CEL** (built-in) | `stave apply --observations …` |",
        "| Prove an attack path *exists* | **Z3 / cvc5 / Yices** | `stave export-sir --format smt2 \\| z3 -in` with a query |",
        "| Enumerate the full blast radius | **Soufflé** | `bash examples/souffle-reachability/run.sh` |",
        "| Enumerate every constraint violation | **Clingo** | `bash examples/clingo-constraints/run.sh` |",
        "| Derive a proof tree (\"why is this reachable?\") | **Prolog** | `bash examples/prolog-proof-trees/run.sh` |",
        "| Boolean compound check (do all five misconfigs co-occur?) | **PySAT** | `bash examples/sat-control-regression/run.sh` |",
        "| Quantify exploitation probability | **Risk model** | `python3 examples/prism-risk-prioritization/risk_model.py` |",
        "| Quantify attacker cost + remediation ROI | **Game theory** | `python3 examples/game-theory-cost/cost_model.py` |",
        "| Measure drift margin from safe to unsafe | **TLA+ (Python BFS)** | `python3 examples/tlaplus-temporal-safety/temporal_check.py` |",
        "| Run **every** engine across all fixtures | **comparison harness** | `bash examples/compare-engines/run.sh` |",
        "",
        "## Cross-engine matrix (compact)",
        "",
        "Vulnerable fixture (`before` / `writeup-config` / similar). Each",
        "row is the headline cell from `multi-engine-results.md`; click",
        "through for full per-fixture detail.",
        "",
        "| Example | CEL | SMT | Soufflé | Risk | Game |",
        "|---|---|---|---|---|---|",
    ]
    for example in sorted(by_example):
        # Pick the most "vulnerable" fixture for the headline row.
        fxs = by_example[example]
        vuln = pick_vulnerable(fxs)
        cel = vuln.get("cel", {})
        smt_q = vuln.get("smt_queries", [])
        # Show first SMT query verdict if any
        smt_str = "—"
        if smt_q:
            verdicts = [q["z3"].get("verdict") for q in smt_q]
            if all(v == "sat" for v in verdicts):
                smt_str = "sat"
            elif "sat" in verdicts:
                smt_str = "sat (some)"
            else:
                smt_str = "unsat"
        souf = vuln.get("souffle") or {}
        rels = souf.get("rels") or {}
        souf_str = (f"{rels.get('anonymous_reachable', 0)} anon, "
                    f"{rels.get('reachable', 0)} total"
                    if souf.get("verdict") == "ok" else "—")
        risk = vuln.get("risk") or {}
        risk_str = (f"P={risk.get('p_exploit_pct'):.0f}%"
                    if risk.get("p_exploit_pct") is not None else "—")
        game = vuln.get("game") or {}
        game_str = game.get("verdict", "—")

        lines.append(
            f"| [{example}]({example}/multi-engine-results.md) | "
            f"{cel.get('findings', 0)} | {smt_str} | "
            f"{souf_str} | {risk_str} | {game_str} |"
        )
    lines.append("")
    lines += [
        "## Quick Start for Your Own Environment",
        "",
        "1. Pick the scenario closest to your concern from the",
        "   pattern groups above.",
        "2. Read its `multi-engine-results.md` to see which engines",
        "   speak about that scenario shape.",
        "3. Replace the bundled `fixtures/<phase>/observations/`",
        "   with your own observation snapshots (extracted via the",
        "   companion `stave-extractor` tooling or hand-authored).",
        "4. Re-run: `bash run.sh` from the example's directory, or",
        "   point the comparison harness at all engines: `bash",
        "   examples/compare-engines/run.sh`.",
        "5. If a particular engine returns empty / `n/a` on your",
        "   fixture, that is documented in the `multi-engine-results.md`",
        "   for the matched example — it's an engine-rule gap, not a",
        "   Stave bug.",
        "",
        "## Engine coverage summary",
        "",
    ]
    # Add coverage histogram per engine
    from collections import Counter
    eng_counts: dict[str, Counter] = {}
    for eng in ("cel", "souffle", "clingo", "prolog", "pysat", "risk", "tla", "game"):
        c = Counter()
        for f in matrix["fixtures"]:
            v = (f.get(eng) or {}).get("verdict", "missing")
            c[v] += 1
        eng_counts[eng] = c

    lines.append("| Engine | Useful | Empty / no-signal | n/a / skipped | Error |")
    lines.append("|---|---:|---:|---:|---:|")
    for eng, c in eng_counts.items():
        useful = sum(v for k, v in c.items()
                     if k not in ("empty", "n/a", "skipped", "error",
                                  "missing", "MINIMAL", "no-path", "SAFE",
                                  "AT_RISK", "COMPLIANT"))
        empty = c.get("empty", 0) + c.get("MINIMAL", 0) + c.get("no-path", 0) \
                + c.get("SAFE", 0) + c.get("AT_RISK", 0) + c.get("COMPLIANT", 0)
        nonapp = c.get("n/a", 0) + c.get("skipped", 0)
        err = c.get("error", 0)
        lines.append(f"| {eng} | {useful} | {empty} | {nonapp} | {err} |")

    lines += [
        "",
        "*Useful* counts cells that surfaced a positive signal",
        "(non-zero finding count, sat verdict, non-trivial",
        "reachability count, P > 0, named compound, etc.).",
        "*Empty / no-signal* counts engine cells that ran but",
        "returned no actionable data — usually because the",
        "fixture is a remediated counterpart or because the",
        "engine's rule program does not have rules for the",
        "fixture's predicate shape.",
        "",
        "Regenerate this catalog with `python3 scripts/h1-matrix/run.py`",
        "followed by `python3 scripts/h1-matrix/render.py` (see",
        "[`scripts/h1-matrix/README.md`](../scripts/h1-matrix/README.md)).",
    ]
    return "\n".join(lines) + "\n"


def describe_example_cel(fixtures: list[dict]) -> str:
    """One-line summary of CEL findings across an example's fixtures."""
    by_phase = {}
    for f in fixtures:
        by_phase[f["fixture"]] = (f["cel"].get("findings", 0),
                                  f["cel"].get("verdict", "?"))
    if len(by_phase) == 0:
        return ""
    parts = [f"{ph}: {n}" for ph, (n, _) in sorted(by_phase.items())]
    return "CEL findings — " + ", ".join(parts) + "."


def pick_vulnerable(fixtures: list[dict]) -> dict:
    """Heuristic: most CEL findings → vulnerable fixture; fall back
    to the first sat SMT query."""
    by_findings = sorted(
        fixtures, key=lambda f: (f["cel"].get("findings", 0)), reverse=True,
    )
    if by_findings and by_findings[0]["cel"].get("findings", 0) > 0:
        return by_findings[0]
    # Try SMT-sat fixtures
    for f in fixtures:
        if any(q["z3"].get("verdict") == "sat" for q in f.get("smt_queries", [])):
            return f
    # Fall back to first
    return fixtures[0]


def main() -> int:
    matrix = json.loads(MATRIX_PATH.read_text())
    by_example = build_matrix(matrix)

    # CATALOG.md
    catalog_path = EXAMPLES / "CATALOG.md"
    catalog_path.write_text(render_catalog(matrix, by_example))
    print(f"wrote {catalog_path}")

    # Per-example multi-engine-results.md
    for example, fxs in sorted(by_example.items()):
        out = EXAMPLES / example / "multi-engine-results.md"
        out.write_text(render_per_example(example, fxs))
        print(f"  wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
