package enforcement

import (
	"strings"
	"testing"

	"github.com/sufield/stave/internal/core/kernel"
)

func TestTerraformResourceName(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"my-bucket", "my_bucket"},
		{"", "bucket"},
		{"---", "bucket"},
		{"123-bucket", "b_123_bucket"},
		{"UPPER-Case", "upper_case"},
	}
	for _, tt := range tests {
		got := terraformResourceName(tt.input)
		if got != tt.want {
			t.Errorf("terraformResourceName(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestRenderPABTerraform(t *testing.T) {
	targets := []BucketTarget{
		{AssetID: "bucket-a", BucketName: testBucketRef("bucket-a")},
	}
	out := RenderPABTerraform(targets)
	if !strings.Contains(out, "aws_s3_bucket_public_access_block") {
		t.Fatal("missing resource type")
	}
	if !strings.Contains(out, "bucket-a") {
		t.Fatal("missing bucket name")
	}
	if !strings.Contains(out, "block_public_acls") {
		t.Fatal("missing PAB attribute")
	}
}

func TestRenderPABTerraform_Empty(t *testing.T) {
	out := RenderPABTerraform(nil)
	if !strings.Contains(out, "Generated by stave") {
		t.Fatal("missing header comment")
	}
}

func TestRenderSCP(t *testing.T) {
	targets := []BucketTarget{
		{AssetID: "bucket-a", BucketName: testBucketRef("bucket-a")},
	}
	out, err := RenderSCP(targets)
	if err != nil {
		t.Fatalf("RenderSCP error: %v", err)
	}
	if !strings.Contains(out, "DenyPublicExposureConfigChanges") {
		t.Fatal("missing SID")
	}
	if !strings.Contains(out, "s3:PutBucketAcl") {
		t.Fatal("missing action")
	}
}

func TestSortTargets(t *testing.T) {
	targets := []BucketTarget{
		{AssetID: "c"},
		{AssetID: "a"},
		{AssetID: "b"},
	}
	SortTargets(targets)
	if targets[0].AssetID != "a" {
		t.Fatalf("[0] = %q", targets[0].AssetID)
	}
}

func TestExtractBucketTargets(t *testing.T) {
	findings := []FindingRef{
		{ControlID: "CTL.S3.PUBLIC.001", AssetID: "bucket-a"},
		{ControlID: "CTL.S3.PUBLIC.002", AssetID: "bucket-b"},
		{ControlID: "CTL.S3.ENCRYPT.001", AssetID: "bucket-c"}, // Not public control
		{ControlID: "CTL.S3.PUBLIC.001", AssetID: "bucket-a"},  // Duplicate
		{ControlID: "CTL.S3.PUBLIC.001", AssetID: ""},          // Empty asset
	}
	targets := ExtractBucketTargets(findings)
	if len(targets) != 2 {
		t.Fatalf("expected 2 targets, got %d", len(targets))
	}
	// Should be sorted
	if targets[0].AssetID != "bucket-a" {
		t.Fatalf("[0] = %q", targets[0].AssetID)
	}
}

func TestExtractBucketTargets_Empty(t *testing.T) {
	targets := ExtractBucketTargets(nil)
	if len(targets) != 0 {
		t.Fatalf("expected 0, got %d", len(targets))
	}
}

// testBucketRef creates a simple BucketRef for testing.
func testBucketRef(name string) kernel.BucketRef {
	return kernel.NewBucketRef(name)
}
