package enforcement

import (
	"encoding/json"
	"sort"
	"strings"
	"unicode"

	"github.com/samber/lo"
	"github.com/sufield/stave/internal/domain/asset"
	"github.com/sufield/stave/internal/domain/kernel"
)

// BucketTarget represents one S3 bucket remediation target.
type BucketTarget struct {
	AssetID    string
	BucketName string
}

// SortTargets sorts targets by resource ID for deterministic output.
func SortTargets(targets []BucketTarget) {
	sort.Slice(targets, func(i, j int) bool {
		return targets[i].AssetID < targets[j].AssetID
	})
}

// RenderPABTerraform renders deterministic Terraform for S3 PAB resources.
func RenderPABTerraform(targets []BucketTarget) string {
	var b strings.Builder
	b.WriteString("# Generated by stave enforce --mode=pab\n\n")
	for _, t := range targets {
		b.WriteString(`resource "aws_s3_bucket_public_access_block" "`)
		b.WriteString(terraformResourceName(t.BucketName))
		b.WriteString("\" {\n")
		b.WriteString(`  bucket = "`)
		b.WriteString(t.BucketName)
		b.WriteString("\"\n")
		b.WriteString("  block_public_acls       = true\n")
		b.WriteString("  ignore_public_acls      = true\n")
		b.WriteString("  block_public_policy     = true\n")
		b.WriteString("  restrict_public_buckets = true\n")
		b.WriteString("}\n\n")
	}
	return b.String()
}

// RenderSCP renders deterministic SCP JSON for bucket policy/ACL mutation deny.
func RenderSCP(targets []BucketTarget) (string, error) {
	type statement struct {
		Sid      string   `json:"Sid"`
		Effect   string   `json:"Effect"`
		Action   []string `json:"Action"`
		Resource []string `json:"Resource"`
	}
	type policy struct {
		Version   string      `json:"Version"`
		Statement []statement `json:"Statement"`
	}

	resources := make([]string, 0, len(targets))
	for _, t := range targets {
		resources = append(resources, "arn:aws:s3:::"+t.BucketName)
	}
	doc := policy{
		Version: "2012-10-17",
		Statement: []statement{
			{
				Sid:    "DenyPublicExposureConfigChanges",
				Effect: "Deny",
				Action: []string{
					"s3:PutBucketAcl",
					"s3:PutBucketPolicy",
				},
				Resource: resources,
			},
		},
	}
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", err
	}
	return string(out) + "\n", nil
}

// FindingRef is a minimal representation of an evaluation finding used for
// target extraction.
type FindingRef struct {
	ControlID kernel.ControlID
	AssetID   asset.ID
}

// ExtractBucketTargets filters findings to S3 public-exposure controls,
// deduplicates by asset ID, and returns sorted bucket targets.
func ExtractBucketTargets(findings []FindingRef) []BucketTarget {
	targets := lo.FilterMap(findings, func(f FindingRef, _ int) (BucketTarget, bool) {
		if !strings.HasPrefix(string(f.ControlID), "CTL.S3.PUBLIC.") {
			return BucketTarget{}, false
		}
		assetID := strings.TrimSpace(f.AssetID.String())
		if assetID == "" {
			return BucketTarget{}, false
		}
		return BucketTarget{AssetID: assetID, BucketName: extractBucketName(assetID)}, true
	})
	targets = lo.UniqBy(targets, func(t BucketTarget) string { return t.AssetID })
	SortTargets(targets)
	return targets
}

func extractBucketName(assetID string) string {
	s := strings.TrimSpace(assetID)
	s = strings.TrimPrefix(s, "arn:aws:s3:::")
	s = strings.TrimPrefix(s, "aws:s3:::")
	s = strings.TrimPrefix(s, "s3://")
	if i := strings.IndexByte(s, '/'); i >= 0 {
		s = s[:i]
	}
	if s == "" {
		return assetID
	}
	return s
}

func terraformResourceName(bucket string) string {
	if bucket == "" {
		return "bucket"
	}
	var b strings.Builder
	for i, r := range bucket {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if i == 0 && unicode.IsDigit(r) {
				b.WriteByte('b')
				b.WriteByte('_')
			}
			b.WriteRune(unicode.ToLower(r))
			continue
		}
		b.WriteByte('_')
	}
	name := b.String()
	name = strings.Trim(name, "_")
	if name == "" {
		return "bucket"
	}
	return name
}
