package sla

import (
	"fmt"
	"io"
	"strings"

	"github.com/spf13/cobra"

	"github.com/sufield/stave/internal/adapters/sla"
	"github.com/sufield/stave/internal/platform/fsutil"
)

type initOptions struct {
	OutFile string
	Profile string
	Stdout  bool
}

func newInitCmd() *cobra.Command {
	opts := &initOptions{
		OutFile: "sla-policy.yaml",
		Profile: "default",
	}

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Generate a starter SLA policy file",
		Long: `Generate a starter SLA policy YAML file with sensible defaults.

Available profiles:
  default   Balanced deadlines (72h/336h/1440h/4320h)
  hipaa     HIPAA-aligned (72h/720h/2160h/4320h)
  fedramp   FedRAMP Moderate (72h/720h/2160h/4320h)
  pci       PCI-DSS v4.0 (24h/168h/720h/2160h)
  strict    Aggressive (24h/72h/168h/720h)

Outputs:
  File at --out path, or stdout with --stdout

Exit Codes:
  0   Policy file generated
  2   Invalid input`,
		Example: `  # Generate default policy
  stave sla init

  # HIPAA-aligned policy
  stave sla init --profile hipaa --out hipaa-sla.yaml

  # Print to stdout
  stave sla init --profile strict --stdout`,
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runInit(cmd.OutOrStdout(), cmd.ErrOrStderr(), opts)
		},
	}

	cmd.Flags().StringVar(&opts.OutFile, "out", "sla-policy.yaml", "output file path")
	cmd.Flags().StringVar(&opts.Profile, "profile", "default", "starter template: default | hipaa | fedramp | pci | strict")
	cmd.Flags().BoolVar(&opts.Stdout, "stdout", false, "print to stdout instead of file")

	return cmd
}

// templateHeader is the comment block prepended to generated policies.
const templateHeader = `# Stave SLA Policy
# Generated by: stave sla init --profile %s
# Edit deadlines to match your organization's policy.
#
# These deadlines are enforced by:
#   stave budget --sla-profile-file %s
#   stave rank   --sla-profile-file %s
#   stave score  --sla-profile-file %s
#
# Validate with: stave sla validate --file %s

`

func runInit(stdout, stderr io.Writer, opts *initOptions) error {
	profileID := resolveProfileID(opts.Profile)
	pol, err := sla.LoadEmbedded(profileID)
	if err != nil {
		return fmt.Errorf("unknown profile %q (available: default, hipaa, fedramp, pci, strict): %w", opts.Profile, err)
	}

	outName := opts.OutFile
	header := fmt.Sprintf(templateHeader, opts.Profile, outName, outName, outName, outName)

	body := formatPolicy(pol)
	content := header + body

	if opts.Stdout {
		_, err := fmt.Fprint(stdout, content)
		return err
	}

	if err := fsutil.SafeWriteFile(outName, []byte(content), fsutil.WriteOptions{
		Perm: 0o644,
	}); err != nil {
		return fmt.Errorf("write sla policy: %w", err)
	}

	fmt.Fprintf(stderr, "Wrote %s (%s profile)\n", outName, opts.Profile)
	fmt.Fprintf(stderr, "Validate with: stave sla validate --file %s\n", outName)
	return nil
}

func resolveProfileID(profile string) string {
	switch strings.ToLower(profile) {
	case "pci":
		return "pci_dss_v4"
	case "fedramp":
		return "fedramp_moderate"
	case "strict":
		return "strict"
	default:
		return profile
	}
}

func formatPolicy(pol *sla.Policy) string {
	var b strings.Builder
	fmt.Fprintf(&b, "id: %s\n", pol.ID)
	fmt.Fprintf(&b, "name: %s\n", pol.Name)
	if pol.Description != "" {
		fmt.Fprintf(&b, "description: >-\n  %s\n", pol.Description)
	}
	fmt.Fprintf(&b, "\ndeadlines:\n")
	fmt.Fprintf(&b, "  critical: %s\n", pol.Deadlines.Critical)
	fmt.Fprintf(&b, "  high:     %s\n", pol.Deadlines.High)
	fmt.Fprintf(&b, "  medium:   %s\n", pol.Deadlines.Medium)
	fmt.Fprintf(&b, "  low:      %s\n", pol.Deadlines.Low)
	fmt.Fprintf(&b, "\nescalation_factor: %.1f\n", pol.EscalationFactor)
	return b.String()
}
