package text

import (
	"fmt"
	"io"
	"time"

	appcontracts "github.com/sufield/stave/internal/app/contracts"
	"github.com/sufield/stave/internal/core/evaluation"
)

// hygieneWriter collects the first write error so callers don't need to check every fmt call.
type hygieneWriter struct {
	w   io.Writer
	err error
}

func (h *hygieneWriter) f(format string, args ...any) {
	if h.err != nil {
		return
	}
	_, h.err = fmt.Fprintf(h.w, format, args...)
}

// WriteHygieneReport writes a hygiene report as markdown to w.
func WriteHygieneReport(w io.Writer, req appcontracts.HygieneAssessment) error {
	ctx := req.AuditContext
	h := &hygieneWriter{w: w}

	h.f("# Snapshot Hygiene Report\n\n")
	h.f("- **Generated At:** %s\n", ctx.Now.Format(time.RFC3339))
	h.f("- **Lookback Period:** %s (since %s)\n", ctx.LookbackWindow, ctx.PreviousAuditAt.Format(time.RFC3339))
	h.f("- **Due Soon Threshold:** %s\n\n", ctx.SLAWarning)

	writeLifecycleTable(h, req.Evidence)
	writeRiskTable(h, req.SLAPosture, ctx.SLAWarning)
	writeTrendTable(h, req.ExposureHistory)

	h.f("\n")
	h.f("> Auto-generated by `stave snapshot hygiene`. Regenerate after snapshot lifecycle operations.\n")
	return h.err
}

func writeLifecycleTable(h *hygieneWriter, stats appcontracts.SnapshotSummary) {
	h.f("## Snapshot Lifecycle\n\n")
	h.f("| Metric | Value |\n| :--- | :--- |\n")
	h.f("| Total snapshots | %d |\n", stats.TotalEvidence())
	h.f("| Active snapshots | %d |\n", stats.ActiveSnapshots)
	h.f("| Archived snapshots | %d |\n", stats.HistoricalEvidence)
	h.f("| Prune candidates (current) | %d |\n", stats.PurgeCandidates)
	h.f("| Retention tier | %s |\n", stats.ComplianceTier)
	h.f("| Retention window | %s |\n", stats.RetentionPolicy)
	h.f("| Keep minimum | %d |\n\n", stats.MinEvidenceCount)
}

func writeRiskTable(h *hygieneWriter, risk appcontracts.SLAPosture, dueSoon time.Duration) {
	h.f("## Current Risk Status\n\n")
	h.f("| Metric | Value |\n| :--- | :--- |\n")
	h.f("| Current violations | %d |\n", risk.ActiveFindings)
	h.f("| Upcoming overdue | %d |\n", risk.SLABreaches)
	h.f("| Upcoming due now | %d |\n", risk.BreachingNow)
	h.f("| Upcoming due soon (<= %s) | %d |\n", dueSoon, risk.NearBreach)
	h.f("| Upcoming later | %d |\n", risk.CompliantWindow)
	h.f("| Upcoming total | %d |\n\n", risk.PendingRemediations())
}

func writeTrendTable(h *hygieneWriter, trends []evaluation.TrendMetric) {
	h.f("## Risk SecurityState & Trends\n\n")
	h.f("| Metric | Current | Previous | Change |\n| :--- | :--- | :--- | :--- |\n")
	for _, trend := range trends {
		// Symbol() already encodes direction (↓ improving, ↑ declining), so render
		// the magnitude of the change to avoid a double-negative like "↓ -3".
		change := trend.Change()
		if change < 0 {
			change = -change
		}
		h.f("| %s | %d | %d | %s%d |\n", trend.Name, trend.Current, trend.Previous, trend.Symbol(), change)
	}
}
