package text

import (
	"fmt"
	"io"
	"time"

	appcontracts "github.com/sufield/stave/internal/app/contracts"
	"github.com/sufield/stave/pkg/alpha/domain/evaluation"
)

// hygieneWriter collects the first write error so callers don't need to check every fmt call.
type hygieneWriter struct {
	w   io.Writer
	err error
}

func (h *hygieneWriter) f(format string, args ...any) {
	if h.err != nil {
		return
	}
	_, h.err = fmt.Fprintf(h.w, format, args...)
}

// WriteHygieneReport writes a hygiene report as markdown to w.
func WriteHygieneReport(w io.Writer, req appcontracts.ReportRequest) error {
	ctx := req.Context
	h := &hygieneWriter{w: w}

	h.f("# Snapshot Hygiene Report\n\n")
	h.f("- **Generated At:** %s\n", ctx.Now.Format(time.RFC3339))
	h.f("- **Lookback Period:** %s (since %s)\n", ctx.Lookback, ctx.PreviousNow.Format(time.RFC3339))
	h.f("- **Due Soon Threshold:** %s\n\n", ctx.DueSoon)

	writeLifecycleTable(h, req.Snapshots)
	writeRiskTable(h, req.Risks, ctx.DueSoon)
	writeTrendTable(h, req.Trends)

	h.f("\n")
	h.f("> Auto-generated by `stave snapshot hygiene`. Regenerate after snapshot lifecycle operations.\n")
	return h.err
}

func writeLifecycleTable(h *hygieneWriter, stats appcontracts.SnapshotStats) {
	h.f("## Lifecycle Inventory\n\n")
	h.f("| Metric | Value |\n| :--- | :--- |\n")
	h.f("| Total snapshots | %d |\n", stats.Total)
	h.f("| Active snapshots | %d |\n", stats.Active)
	h.f("| Archived snapshots | %d |\n", stats.Archived)
	h.f("| Prune candidates (current) | %d |\n", stats.PruneCandidates)
	h.f("| Retention tier | %s |\n", stats.RetentionTier)
	h.f("| Retention window | %s |\n", stats.RetentionDuration)
	h.f("| Keep minimum | %d |\n\n", stats.KeepMin)
}

func writeRiskTable(h *hygieneWriter, risk appcontracts.RiskStats, dueSoon time.Duration) {
	h.f("## Current Risk Status\n\n")
	h.f("| Metric | Value |\n| :--- | :--- |\n")
	h.f("| Current violations | %d |\n", risk.CurrentViolations)
	h.f("| Upcoming overdue | %d |\n", risk.Overdue)
	h.f("| Upcoming due now | %d |\n", risk.DueNow)
	h.f("| Upcoming due soon (<= %s) | %d |\n", dueSoon, risk.DueSoon)
	h.f("| Upcoming later | %d |\n", risk.Later)
	h.f("| Upcoming total | %d |\n\n", risk.UpcomingTotal)
}

func writeTrendTable(h *hygieneWriter, trends []evaluation.TrendMetric) {
	h.f("## Risk Posture & Trends\n\n")
	h.f("| Metric | Current | Previous | Change |\n| :--- | :--- | :--- | :--- |\n")
	for _, trend := range trends {
		h.f("| %s | %d | %d | %s%d |\n", trend.Name, trend.Current, trend.Previous, trend.Symbol(), trend.Change())
	}
}
