package text

import (
	"fmt"
	"io"
	"time"

	"github.com/sufield/stave/internal/app/hygiene"
)

// WriteHygieneReport writes a hygiene report as markdown to w.
func WriteHygieneReport(w io.Writer, req hygiene.ReportRequest) error {
	ctx := req.Context

	fmt.Fprint(w, "# Snapshot Hygiene Report\n\n")
	fmt.Fprintf(w, "- **Generated At:** %s\n", ctx.Now.Format(time.RFC3339))
	fmt.Fprintf(w, "- **Lookback Period:** %s (since %s)\n", ctx.Lookback, ctx.PreviousNow.Format(time.RFC3339))
	fmt.Fprintf(w, "- **Due Soon Threshold:** %s\n\n", ctx.DueSoon)

	writeLifecycleTable(w, req.Snapshots)
	writeRiskTable(w, req.Risks, ctx.DueSoon)
	writeTrendTable(w, req.Trends)

	fmt.Fprint(w, "\n")
	fmt.Fprint(w, "> Auto-generated by `stave snapshot hygiene`. Regenerate after snapshot lifecycle operations.\n")
	return nil
}

func writeLifecycleTable(w io.Writer, stats hygiene.SnapshotStats) {
	fmt.Fprint(w, "## Lifecycle Inventory\n\n")
	fmt.Fprint(w, "| Metric | Value |\n| :--- | :--- |\n")
	fmt.Fprintf(w, "| Total snapshots | %d |\n", stats.Total)
	fmt.Fprintf(w, "| Active snapshots | %d |\n", stats.Active)
	fmt.Fprintf(w, "| Archived snapshots | %d |\n", stats.Archived)
	fmt.Fprintf(w, "| Prune candidates (current) | %d |\n", stats.PruneCandidates)
	fmt.Fprintf(w, "| Retention tier | %s |\n", stats.RetentionTier)
	fmt.Fprintf(w, "| Retention window | %s |\n", stats.RetentionDuration)
	fmt.Fprintf(w, "| Keep minimum | %d |\n\n", stats.KeepMin)
}

func writeRiskTable(w io.Writer, risk hygiene.RiskStats, dueSoon time.Duration) {
	fmt.Fprint(w, "## Current Risk Status\n\n")
	fmt.Fprint(w, "| Metric | Value |\n| :--- | :--- |\n")
	fmt.Fprintf(w, "| Current violations | %d |\n", risk.CurrentViolations)
	fmt.Fprintf(w, "| Upcoming overdue | %d |\n", risk.Overdue)
	fmt.Fprintf(w, "| Upcoming due now | %d |\n", risk.DueNow)
	fmt.Fprintf(w, "| Upcoming due soon (<= %s) | %d |\n", dueSoon, risk.DueSoon)
	fmt.Fprintf(w, "| Upcoming later | %d |\n", risk.Later)
	fmt.Fprintf(w, "| Upcoming total | %d |\n\n", risk.UpcomingTotal)
}

func writeTrendTable(w io.Writer, trends []hygiene.TrendMetric) {
	fmt.Fprint(w, "## Risk Posture & Trends\n\n")
	fmt.Fprint(w, "| Metric | Current | Previous | Change |\n| :--- | :--- | :--- | :--- |\n")
	for _, trend := range trends {
		change := trend.Current - trend.Previous
		symbol := ""
		if change > 0 {
			symbol = "↑ "
		} else if change < 0 {
			symbol = "↓ "
		}
		fmt.Fprintf(w, "| %s | %d | %d | %s%d |\n", trend.Name, trend.Current, trend.Previous, symbol, change)
	}
}
