package text

import (
	"fmt"
	"strings"
	"time"

	"github.com/sufield/stave/internal/pkg/timeutil"
)

// UpcomingItem represents a single upcoming snapshot action item for rendering.
type UpcomingItem struct {
	DueAt          time.Time
	Status         string
	ControlID      string
	AssetID        string
	AssetType      string
	FirstUnsafeAt  time.Time
	LastSeenUnsafe time.Time
	Threshold      time.Duration
	Remaining      time.Duration
}

// UpcomingSummary holds aggregate counts for upcoming items by status.
type UpcomingSummary struct {
	Overdue int
	DueNow  int
	DueSoon int
	Later   int
	Total   int
}

// UpcomingRenderOptions holds configuration for rendering upcoming markdown.
type UpcomingRenderOptions struct {
	Now              time.Time
	DueSoonThreshold time.Duration
}

// RenderUpcomingMarkdown renders a full upcoming report as a Markdown string.
func RenderUpcomingMarkdown(items []UpcomingItem, summary UpcomingSummary, opts UpcomingRenderOptions) string {
	var b strings.Builder
	b.WriteString("# Upcoming Snapshot Action Items\n\n")
	b.WriteString("> Auto-generated by `stave upcoming`. Do not edit manually; regenerate after each new snapshot capture.\n\n")
	fmt.Fprintf(&b, "Generated at: `%s`\n\n", opts.Now.UTC().Format(time.RFC3339))
	b.WriteString(RenderUpcomingSummaryMarkdown(summary, opts.DueSoonThreshold))
	b.WriteString("\n")

	if len(items) == 0 {
		b.WriteString("No upcoming snapshot action items.\n")
		return b.String()
	}

	b.WriteString("| Due At (UTC) | Status | Control | Asset | Type | First Unsafe | Last Seen Unsafe | Threshold | Time To Due |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, item := range items {
		fmt.Fprintf(&b,
			"| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n",
			item.DueAt.Format(time.RFC3339),
			item.Status,
			item.ControlID,
			item.AssetID,
			item.AssetType,
			item.FirstUnsafeAt.Format(time.RFC3339),
			item.LastSeenUnsafe.Format(time.RFC3339),
			timeutil.FormatDuration(item.Threshold),
			FormatRemaining(item.Remaining),
		)
	}
	return b.String()
}

// RenderUpcomingSummaryMarkdown renders only the summary section as Markdown.
func RenderUpcomingSummaryMarkdown(summary UpcomingSummary, dueSoonThreshold time.Duration) string {
	var b strings.Builder
	b.WriteString("## Snapshot SLA Summary\n\n")
	fmt.Fprintf(&b, "- Overdue: **%d**\n", summary.Overdue)
	fmt.Fprintf(&b, "- Due now: **%d**\n", summary.DueNow)
	fmt.Fprintf(&b, "- Due soon (<= %s): **%d**\n", timeutil.FormatDurationHuman(dueSoonThreshold), summary.DueSoon)
	fmt.Fprintf(&b, "- Later: **%d**\n", summary.Later)
	fmt.Fprintf(&b, "- Total action items: **%d**\n", summary.Total)
	return b.String()
}

// FormatRemaining formats a duration for the "Time To Due" column.
func FormatRemaining(d time.Duration) string {
	switch {
	case d == 0:
		return "0h"
	case d < 0:
		return "-" + timeutil.FormatDurationHuman(-d)
	default:
		return timeutil.FormatDurationHuman(d)
	}
}
