package text

import (
	"strconv"
	"strings"
	"time"

	"github.com/sufield/stave/internal/core/asset"
	"github.com/sufield/stave/internal/core/kernel"
)

// UpcomingItem represents a single upcoming snapshot action item for rendering.
type UpcomingItem struct {
	DueAt          time.Time
	Status         string
	ControlID      kernel.ControlID
	AssetID        asset.ID
	AssetType      kernel.AssetType
	FirstUnsafeAt  time.Time
	LastSeenUnsafe time.Time
	Threshold      time.Duration
	Remaining      time.Duration
}

// UpcomingSummary holds aggregate counts for upcoming items by status.
type UpcomingSummary struct {
	Overdue int
	DueNow  int
	DueSoon int
	Later   int
	Total   int
}

// UpcomingRenderOptions holds configuration for rendering upcoming markdown.
type UpcomingRenderOptions struct {
	EvalTime         time.Time
	DueSoonThreshold time.Duration
}

// RenderUpcomingMarkdown renders a full upcoming report as a Markdown string.
func RenderUpcomingMarkdown(items []UpcomingItem, summary UpcomingSummary, opts UpcomingRenderOptions) string {
	var b strings.Builder
	b.WriteString("# Upcoming Snapshot Action Items\n\n")
	b.WriteString("> Auto-generated by `stave upcoming`. Do not edit manually; regenerate after each new snapshot capture.\n\n")
	b.WriteString("Generated at: `")
	b.WriteString(opts.EvalTime.UTC().Format(time.RFC3339))
	b.WriteString("`\n\n")
	b.WriteString(RenderUpcomingSummaryMarkdown(summary, opts.DueSoonThreshold))
	b.WriteString("\n")

	if len(items) == 0 {
		b.WriteString("No upcoming snapshot action items.\n")
		return b.String()
	}

	b.WriteString("| Due At (UTC) | Status | Control | Asset | Type | First Unsafe | Last Seen Unsafe | Threshold | Time To Due |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for i := range items {
		item := &items[i]
		b.WriteString("| ")
		b.WriteString(item.DueAt.Format(time.RFC3339))
		b.WriteString(" | ")
		b.WriteString(item.Status)
		b.WriteString(" | ")
		b.WriteString(string(item.ControlID))
		b.WriteString(" | ")
		b.WriteString(string(item.AssetID))
		b.WriteString(" | ")
		b.WriteString(string(item.AssetType))
		b.WriteString(" | ")
		b.WriteString(item.FirstUnsafeAt.Format(time.RFC3339))
		b.WriteString(" | ")
		b.WriteString(item.LastSeenUnsafe.Format(time.RFC3339))
		b.WriteString(" | ")
		b.WriteString(kernel.FormatDuration(item.Threshold))
		b.WriteString(" | ")
		b.WriteString(FormatRemaining(item.Remaining))
		b.WriteString(" |\n")
	}
	return b.String()
}

// RenderUpcomingSummaryMarkdown renders only the summary section as Markdown.
func RenderUpcomingSummaryMarkdown(summary UpcomingSummary, dueSoonThreshold time.Duration) string {
	var b strings.Builder
	b.WriteString("## Snapshot SLA Summary\n\n")
	b.WriteString("- Overdue: **")
	b.WriteString(strconv.Itoa(summary.Overdue))
	b.WriteString("**\n- Due now: **")
	b.WriteString(strconv.Itoa(summary.DueNow))
	b.WriteString("**\n- Due soon (<= ")
	b.WriteString(kernel.FormatDurationHuman(dueSoonThreshold))
	b.WriteString("): **")
	b.WriteString(strconv.Itoa(summary.DueSoon))
	b.WriteString("**\n- Later: **")
	b.WriteString(strconv.Itoa(summary.Later))
	b.WriteString("**\n- Total action items: **")
	b.WriteString(strconv.Itoa(summary.Total))
	b.WriteString("**\n")
	return b.String()
}

// FormatRemaining formats a duration for the "Time To Due" column.
func FormatRemaining(d time.Duration) string {
	switch {
	case d == 0:
		return "0h"
	case d < 0:
		return "-" + kernel.FormatDurationHuman(-d)
	default:
		return kernel.FormatDurationHuman(d)
	}
}
