package hygiene

import (
	"fmt"
	"strings"
	"time"
)

// ReportRequest bundles all data required to generate a hygiene report.
type ReportRequest struct {
	Context   ReportContext
	Snapshots SnapshotStats
	Risks     RiskStats
	Trends    []TrendMetric
}

// ReportContext provides the temporal metadata for the report.
type ReportContext struct {
	Now         time.Time
	PreviousNow time.Time
	Lookback    time.Duration
	DueSoon     time.Duration
}

// RenderMarkdown converts the hygiene data into the final report string.
// It has no dependency on Cobra or the filesystem; it only depends on app types.
func (req ReportRequest) RenderMarkdown() string {
	var b strings.Builder
	ctx := req.Context

	b.WriteString("# Snapshot Hygiene Report\n\n")
	fmt.Fprintf(&b, "- **Generated At:** %s\n", ctx.Now.Format(time.RFC3339))
	fmt.Fprintf(&b, "- **Lookback Period:** %s (since %s)\n", ctx.Lookback, ctx.PreviousNow.Format(time.RFC3339))
	fmt.Fprintf(&b, "- **Due Soon Threshold:** %s\n\n", ctx.DueSoon)

	renderLifecycleTable(&b, req.Snapshots)
	renderRiskTable(&b, req.Risks, ctx.DueSoon)
	renderTrendTable(&b, req.Trends)

	b.WriteString("\n")
	b.WriteString("> Auto-generated by `stave snapshot hygiene`. Regenerate after snapshot lifecycle operations.\n")
	return b.String()
}

func renderLifecycleTable(b *strings.Builder, stats SnapshotStats) {
	b.WriteString("## Lifecycle Inventory\n\n")
	b.WriteString("| Metric | Value |\n| :--- | :--- |\n")
	fmt.Fprintf(b, "| Total snapshots | %d |\n", stats.Total)
	fmt.Fprintf(b, "| Active snapshots | %d |\n", stats.Active)
	fmt.Fprintf(b, "| Archived snapshots | %d |\n", stats.Archived)
	fmt.Fprintf(b, "| Prune candidates (current) | %d |\n", stats.PruneCandidates)
	fmt.Fprintf(b, "| Retention tier | %s |\n", stats.RetentionTier)
	fmt.Fprintf(b, "| Retention window | %s |\n", stats.RetentionDuration)
	fmt.Fprintf(b, "| Keep minimum | %d |\n\n", stats.KeepMin)
}

func renderRiskTable(b *strings.Builder, risk RiskStats, dueSoon time.Duration) {
	b.WriteString("## Current Risk Status\n\n")
	b.WriteString("| Metric | Value |\n| :--- | :--- |\n")
	fmt.Fprintf(b, "| Current violations | %d |\n", risk.CurrentViolations)
	fmt.Fprintf(b, "| Upcoming overdue | %d |\n", risk.Overdue)
	fmt.Fprintf(b, "| Upcoming due now | %d |\n", risk.DueNow)
	fmt.Fprintf(b, "| Upcoming due soon (<= %s) | %d |\n", dueSoon, risk.DueSoon)
	fmt.Fprintf(b, "| Upcoming later | %d |\n", risk.Later)
	fmt.Fprintf(b, "| Upcoming total | %d |\n\n", risk.UpcomingTotal)
}

func renderTrendTable(b *strings.Builder, trends []TrendMetric) {
	b.WriteString("## Risk Posture & Trends\n\n")
	b.WriteString("| Metric | Current | Previous | Change |\n| :--- | :--- | :--- | :--- |\n")
	for _, trend := range trends {
		change := trend.Current - trend.Previous
		symbol := ""
		if change > 0 {
			symbol = "↑ "
		} else if change < 0 {
			symbol = "↓ "
		}
		fmt.Fprintf(b, "| %s | %d | %d | %s%d |\n", trend.Name, trend.Current, trend.Previous, symbol, change)
	}
}
