// Package controldata holds the embedded built-in control YAML files.
//
// The embedded/ directory is populated at build time by "make sync-controls",
// which copies canonical control definitions from the top-level controls/
// directory. The embed.FS is exported so that adapter and test packages can
// access the bundled controls without knowing the physical file layout.
package controldata

import "embed"

//go:embed embedded/s3/**/*.yaml embedded/iam/**/*.yaml embedded/gcs/**/*.yaml embedded/dns/**/*.yaml embedded/vpc/**/*.yaml embedded/ec2/**/*.yaml embedded/rds/**/*.yaml embedded/elb/**/*.yaml embedded/k8s/**/*.yaml embedded/backup/**/*.yaml embedded/apigateway/**/*.yaml embedded/autoscaling/**/*.yaml embedded/cloudformation/**/*.yaml embedded/cloudtrail/**/*.yaml embedded/cloudwatch/**/*.yaml embedded/cognito/**/*.yaml embedded/config/**/*.yaml embedded/dynamodb/**/*.yaml embedded/ecr/**/*.yaml embedded/elasticache/**/*.yaml embedded/guardduty/**/*.yaml embedded/kms/**/*.yaml embedded/opensearch/**/*.yaml embedded/route53/**/*.yaml embedded/secretsmanager/**/*.yaml embedded/securityhub/**/*.yaml embedded/sns/*.yaml embedded/sns/**/*.yaml embedded/sqs/**/*.yaml embedded/efs/**/*.yaml embedded/exposure/**/*.yaml embedded/waf/**/*.yaml embedded/guardrail/*.yaml embedded/lambda/**/*.yaml embedded/lifecycle/**/*.yaml embedded/org/*.yaml embedded/org/**/*.yaml embedded/acm/*.yaml embedded/acm/**/*.yaml embedded/cloud9/**/*.yaml embedded/cloudfront/**/*.yaml embedded/eks/*.yaml embedded/eks/**/*.yaml embedded/ecs/**/*.yaml embedded/batch/**/*.yaml embedded/shield/*.yaml embedded/codecommit/**/*.yaml embedded/ssm/**/*.yaml embedded/ad/**/*.yaml embedded/amplify/**/*.yaml embedded/apprunner/**/*.yaml embedded/vsphere/**/*.yaml embedded/cisco/**/*.yaml embedded/redshift/**/*.yaml embedded/neptune/**/*.yaml embedded/documentdb/**/*.yaml embedded/glacier/**/*.yaml embedded/glue/**/*.yaml embedded/codebuild/**/*.yaml embedded/codepipeline/**/*.yaml embedded/sagemaker/**/*.yaml embedded/bedrock/**/*.yaml embedded/emr/**/*.yaml embedded/firehose/**/*.yaml embedded/kinesis/**/*.yaml embedded/msk/**/*.yaml embedded/mwaa/**/*.yaml embedded/apigatewayv2/**/*.yaml embedded/dms/**/*.yaml embedded/eventbridge/**/*.yaml embedded/networkfirewall/**/*.yaml embedded/stepfunctions/**/*.yaml embedded/mq/**/*.yaml embedded/lightsail/**/*.yaml embedded/workspaces/**/*.yaml embedded/beanstalk/**/*.yaml embedded/inspector2/*.yaml embedded/macie/*.yaml embedded/macie/**/*.yaml embedded/athena/**/*.yaml embedded/appstream/**/*.yaml embedded/azure/**/*.yaml embedded/gcp/**/*.yaml embedded/github/**/*.yaml embedded/cloudflare/**/*.yaml embedded/m365/**/*.yaml embedded/ram/*.yaml embedded/compliance/**/*.yaml embedded/dataclass/**/*.yaml embedded/model/**/*.yaml embedded/auditmanager/*.yaml embedded/fms/*.yaml embedded/grafana/*.yaml embedded/securitylake/*.yaml embedded/servicecatalog/*.yaml embedded/ses/**/*.yaml embedded/transfer/**/*.yaml all:embedded/_triage/families/*.yaml all:embedded/_triage/overrides/*.yaml

// FS provides read-only access to the embedded built-in control YAML files.
var FS embed.FS
