package main

import (
	"bytes"
	"encoding/json"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func scanSrc(t *testing.T, src string) []Goroutine {
	t.Helper()
	fset := token.NewFileSet()
	gs, err := scanFileSource(fset, "test.go", []byte(src))
	if err != nil {
		t.Fatalf("scanFileSource: %v", err)
	}
	return gs
}

func TestScan_UnmanagedGoroutine(t *testing.T) {
	gs := scanSrc(t, `package p
func Worker() {
	go doWork()
}
func doWork() {}
`)
	if len(gs) != 1 {
		t.Fatalf("want 1 goroutine, got %d: %+v", len(gs), gs)
	}
	g := gs[0]
	if g.Managed {
		t.Errorf("want unmanaged, got managed; signals=%v", g.Signals)
	}
	if g.Func != "Worker" {
		t.Errorf("want func Worker, got %q", g.Func)
	}
	if len(g.Signals) != 0 {
		t.Errorf("want no signals, got %v", g.Signals)
	}
}

func TestScan_WaitGroupManaged(t *testing.T) {
	gs := scanSrc(t, `package p
import "sync"
func Run() {
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		work()
	}()
	wg.Wait()
}
func work() {}
`)
	if len(gs) != 1 {
		t.Fatalf("want 1, got %d", len(gs))
	}
	if !gs[0].Managed {
		t.Errorf("want managed via waitgroup, signals=%v", gs[0].Signals)
	}
}

func TestScan_ContextManaged(t *testing.T) {
	gs := scanSrc(t, `package p
import "context"
func Loop(ctx context.Context) {
	go func() {
		for {
			select {
			case <-ctx.Done():
				return
			}
		}
	}()
}
`)
	if len(gs) != 1 {
		t.Fatalf("want 1, got %d", len(gs))
	}
	if !gs[0].Managed {
		t.Errorf("want managed via context, signals=%v", gs[0].Signals)
	}
}

func TestScan_ChannelResultManaged(t *testing.T) {
	gs := scanSrc(t, `package p
func Compute() int {
	ch := make(chan int)
	go func() { ch <- 42 }()
	return <-ch
}
`)
	if len(gs) != 1 {
		t.Fatalf("want 1, got %d", len(gs))
	}
	if !gs[0].Managed {
		t.Errorf("want managed via chan-recv, signals=%v", gs[0].Signals)
	}
}

func TestScan_NestedClosureUnmanaged(t *testing.T) {
	gs := scanSrc(t, `package p
func Outer() {
	helper := func() {
		go fireAndForget()
	}
	helper()
}
func fireAndForget() {}
`)
	if len(gs) != 1 {
		t.Fatalf("want 1, got %d", len(gs))
	}
	if gs[0].Managed {
		t.Errorf("want unmanaged, signals=%v", gs[0].Signals)
	}
	if gs[0].Func != "Outer" {
		t.Errorf("want enclosing decl Outer, got %q", gs[0].Func)
	}
}

func TestScan_MultipleSortedByLine(t *testing.T) {
	gs := scanSrc(t, `package p
func A() {
	go one()
	go two()
}
func one() {}
func two() {}
`)
	if len(gs) != 2 {
		t.Fatalf("want 2, got %d", len(gs))
	}
	if gs[0].Line >= gs[1].Line {
		t.Errorf("want sorted by line, got %d then %d", gs[0].Line, gs[1].Line)
	}
}

func TestScanDir_SkipsTestAndGenerated(t *testing.T) {
	dir := t.TempDir()
	write := func(name, content string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("prod.go", "package p\nfunc F() { go g() }\nfunc g() {}\n")
	write("prod_test.go", "package p\nimport \"testing\"\nfunc TestX(t *testing.T) { go g2() }\nfunc g2() {}\n")
	write("gen.go", "// Code generated by tool. DO NOT EDIT.\npackage p\nfunc H() { go g3() }\nfunc g3() {}\n")

	gs, err := scanDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(gs) != 1 {
		t.Fatalf("want 1 (only prod.go), got %d: %+v", len(gs), gs)
	}
	if !strings.HasSuffix(gs[0].File, "prod.go") {
		t.Errorf("want prod.go, got %s", gs[0].File)
	}
}

func TestRun_EmitsDeterministicJSON(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "a.go"),
		[]byte("package p\nfunc F() { go x() }\nfunc x() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var b1, b2 bytes.Buffer
	if err := run(config{Root: dir, Out: &b1}); err != nil {
		t.Fatal(err)
	}
	if err := run(config{Root: dir, Out: &b2}); err != nil {
		t.Fatal(err)
	}
	if b1.String() != b2.String() {
		t.Errorf("non-deterministic output:\n%s\n---\n%s", b1.String(), b2.String())
	}
	var res Result
	if err := json.Unmarshal(b1.Bytes(), &res); err != nil {
		t.Fatalf("invalid JSON: %v", err)
	}
	if res.Schema != schemaVersion {
		t.Errorf("schema=%q want %q", res.Schema, schemaVersion)
	}
	if res.Summary.Total != 1 || res.Summary.Unmanaged != 1 {
		t.Errorf("summary=%+v want total=1 unmanaged=1", res.Summary)
	}
	// Regression: an unmanaged goroutine must emit "signals": [] (not null),
	// or downstream jq/aggregation chokes on a null array.
	if strings.Contains(b1.String(), `"signals": null`) {
		t.Errorf("signals must serialize as [] not null:\n%s", b1.String())
	}
}
