# Generated by stave enforce --mode=pab

resource "aws_s3_bucket_public_access_block" "a_public_bucket" {
  bucket = "a-public-bucket"
  block_public_acls       = true
  ignore_public_acls      = true
  block_public_policy     = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_public_access_block" "z_latent_bucket" {
  bucket = "z-latent-bucket"
  block_public_acls       = true
  ignore_public_acls      = true
  block_public_policy     = true
  restrict_public_buckets = true
}

