package attest

import (
	"crypto/ed25519"
	"testing"
	"time"

	"github.com/sufield/stave/internal/core/asset"
)

func TestVerifyAssets_RejectsFingerprintMismatch(t *testing.T) {
	pubKeyA, privKeyA, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair failed: %v", err)
	}
	_, privKeyB, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair B failed: %v", err)
	}

	assets := []asset.Asset{{ID: "asset-1", Type: "aws_s3_bucket"}}

	// Sign assets with privKeyA to generate attestation carrying pubKeyA's fingerprint
	attestation, err := SignAssets(assets, privKeyA, "host", "1.0", time.Now())
	if err != nil {
		t.Fatalf("SignAssets failed: %v", err)
	}

	// Forge signature using privKeyB (valid signature under privKeyB), but keeping pubKeyA's fingerprint
	canonical, _ := SignAssets(assets, privKeyB, "host", "1.0", time.Now())
	attestation.Signature = canonical.Signature // signature generated by Key B, while fingerprint belongs to Key A

	// Verifying with Key B should fail because pubKeyB's fingerprint does not match attestation.PublicKeyFingerprint (Key A)
	pubKeyB := privKeyB.Public().(ed25519.PublicKey)
	_ = pubKeyA // pubKeyA is the owner of attestation.PublicKeyFingerprint

	err = VerifyAssets(assets, attestation, pubKeyB)
	if err == nil {
		t.Fatalf("expected VerifyAssets to return error for fingerprint mismatch, but it succeeded")
	}
}
