package graph

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"strings"
)

// nodeIDFieldMap maps node types to their unique ID property for MERGE.
var nodeIDFieldMap = map[string]string{
	"Finding":               "finding_id",
	"Resource":              "resource_arn",
	"Control":               "control_id",
	"ThreatChain":           "chain_id",
	"ComplianceRequirement": "id",
	"AttackerCapability":    "chain_id",
	"RemediationAction":     "finding_id",
	"TenantScope":           "account_id",
	"Identity":              "principal_arn",
}

// resourceClassLabel maps resource_class to the additional Neo4j label.
var resourceClassLabel = map[string]string{
	"storage":   "StorageResource",
	"database":  "DatabaseResource",
	"compute":   "ComputeResource",
	"instance":  "InstanceResource",
	"container": "ContainerResource",
	"network":   "NetworkResource",
	"identity":  "IdentityResource",
	"key":       "KeyResource",
	"secret":    "SecretResource",
	"cdn":       "CdnResource",
	"dns":       "DnsResource",
	"registry":  "RegistryResource",
	"queue":     "QueueResource",
	"log":       "LogResource",
}

// MarshalCypher writes Neo4j MERGE statements from GraphData. Returns the
// first underlying writer error, if any.
func MarshalCypher(w io.Writer, g *GraphData) error {
	if g == nil {
		return fmt.Errorf("MarshalCypher: nil GraphData")
	}
	cw := &cypherWriter{w: w}

	cw.printf("// Generated by stave graph export --format neo4j-cypher\n")
	cw.printf("// Schema version: %s  Ontology version: %s\n", g.SchemaVersion, g.OntologyVersion)
	cw.printf("// Generated: %s\n", g.GeneratedAt.Format("2006-01-02T15:04:05Z"))
	cw.printf("// Apply docs/integrations/neo4j/schema.cypher before importing.\n\n")

	// Pre-build a node-ID → type lookup so edge serialization is O(N+M)
	// rather than O(N×M), and so dangling edge references can be flagged
	// rather than silently emitting a fallback "Node" label.
	nodeTypes := make(map[string]string, len(g.Nodes))
	for i := range g.Nodes {
		nodeTypes[g.Nodes[i].ID] = g.Nodes[i].Type
	}

	// Nodes.
	cw.println("// --- Nodes ---")
	for i := range g.Nodes {
		n := &g.Nodes[i]
		labels := cypherLabels(n)
		idField := nodeIDFieldMap[n.Type]
		if idField == "" {
			idField = "id"
		}

		props := flattenCypherProps(n.Properties)
		props["id"] = n.ID // always set the generic id

		cw.printf("MERGE (n:%s {%s: %s})\n", labels, idField, cypherValue(n.ID))
		cw.printf("SET n += %s;\n\n", cypherMap(props))
	}

	// Edges.
	cw.println("// --- Edges ---")
	for i := range g.Edges {
		e := &g.Edges[i]

		fromLabel, ok := nodeTypes[e.From]
		if !ok {
			cw.err = fmt.Errorf("dangling edge: source node %q not present", e.From)
			return cw.err
		}
		toLabel, ok := nodeTypes[e.To]
		if !ok {
			cw.err = fmt.Errorf("dangling edge: target node %q not present", e.To)
			return cw.err
		}

		cw.printf("MATCH (a:%s {id: %s})\n", fromLabel, cypherValue(e.From))
		cw.printf("MATCH (b:%s {id: %s})\n", toLabel, cypherValue(e.To))
		cw.printf("MERGE (a)-[:%s]->(b);\n\n", e.Type)
	}

	return cw.err
}

// cypherWriter wraps an io.Writer and tracks the first error encountered.
// Subsequent writes are short-circuited so MarshalCypher can return the
// original error rather than masking it with a downstream success.
type cypherWriter struct {
	w   io.Writer
	err error
}

func (c *cypherWriter) printf(format string, args ...any) {
	if c.err != nil {
		return
	}
	if _, err := fmt.Fprintf(c.w, format, args...); err != nil {
		c.err = err
	}
}

func (c *cypherWriter) println(s string) {
	if c.err != nil {
		return
	}
	if _, err := fmt.Fprintln(c.w, s); err != nil {
		c.err = err
	}
}

func cypherLabels(n *Node) string {
	labels := n.Type
	if n.Type == "Resource" {
		if rc, ok := n.Properties["resource_class"].(string); ok {
			if extra := resourceClassLabel[rc]; extra != "" {
				labels += ":" + extra
			}
		}
	}
	return labels
}

func cypherValue(v any) string {
	switch val := v.(type) {
	case string:
		return "'" + strings.ReplaceAll(val, "'", "''") + "'"
	case bool:
		if val {
			return "true"
		}
		return "false"
	case float64:
		return fmt.Sprintf("%g", val)
	case int:
		return strconv.Itoa(val)
	case []string:
		parts := make([]string, len(val))
		for i, s := range val {
			parts[i] = cypherValue(s)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case []any:
		parts := make([]string, len(val))
		for i, item := range val {
			parts[i] = cypherValue(item)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	default:
		data, _ := json.Marshal(v)
		return "'" + strings.ReplaceAll(string(data), "'", "''") + "'"
	}
}

func cypherMap(props map[string]any) string {
	var parts []string
	for k, v := range props {
		parts = append(parts, fmt.Sprintf("%s: %s", k, cypherValue(v)))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func flattenCypherProps(props map[string]any) map[string]any {
	flat := make(map[string]any)
	for k, v := range props {
		switch val := v.(type) {
		case map[string]any:
			for sk, sv := range val {
				flat[k+"."+sk] = sv
			}
		case []map[string]string:
			data, _ := json.Marshal(val)
			flat[k] = string(data)
		default:
			flat[k] = v
		}
	}
	return flat
}
