package graph

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"strings"
)

// nodeIDFieldMap maps node types to their unique ID property for MERGE.
var nodeIDFieldMap = map[string]string{
	"Finding":               "finding_id",
	"Resource":              "resource_arn",
	"Control":               "control_id",
	"ThreatChain":           "chain_id",
	"ComplianceRequirement": "id",
	"AttackerCapability":    "chain_id",
	"RemediationAction":     "finding_id",
	"TenantScope":           "account_id",
	"Identity":              "principal_arn",
}

// resourceClassLabel maps resource_class to the additional Neo4j label.
var resourceClassLabel = map[string]string{
	"storage":   "StorageResource",
	"database":  "DatabaseResource",
	"compute":   "ComputeResource",
	"instance":  "InstanceResource",
	"container": "ContainerResource",
	"network":   "NetworkResource",
	"identity":  "IdentityResource",
	"key":       "KeyResource",
	"secret":    "SecretResource",
	"cdn":       "CdnResource",
	"dns":       "DnsResource",
	"registry":  "RegistryResource",
	"queue":     "QueueResource",
	"log":       "LogResource",
}

// MarshalCypher writes Neo4j MERGE statements from GraphData.
func MarshalCypher(w io.Writer, g *GraphData) error {
	fmt.Fprintf(w, "// Generated by stave graph export --format neo4j-cypher\n")
	fmt.Fprintf(w, "// Schema version: %s  Ontology version: %s\n", g.SchemaVersion, g.OntologyVersion)
	fmt.Fprintf(w, "// Generated: %s\n", g.GeneratedAt.Format("2006-01-02T15:04:05Z"))
	fmt.Fprintf(w, "// Apply docs/integrations/neo4j/schema.cypher before importing.\n\n")

	// Nodes.
	fmt.Fprintln(w, "// --- Nodes ---")
	for i := range g.Nodes {
		n := &g.Nodes[i]
		labels := cypherLabels(n)
		idField := nodeIDFieldMap[n.Type]
		if idField == "" {
			idField = "id"
		}

		props := flattenCypherProps(n.Properties)
		props["id"] = n.ID // always set the generic id

		fmt.Fprintf(w, "MERGE (n:%s {%s: %s})\n",
			labels, idField, cypherValue(n.ID))
		fmt.Fprintf(w, "SET n += %s;\n\n", cypherMap(props))
	}

	// Edges.
	fmt.Fprintln(w, "// --- Edges ---")
	for i := range g.Edges {
		e := &g.Edges[i]

		fromLabel, fromID := cypherMatchNode(g, e.From)
		toLabel, toID := cypherMatchNode(g, e.To)

		fmt.Fprintf(w, "MATCH (a:%s {id: %s})\n", fromLabel, cypherValue(fromID))
		fmt.Fprintf(w, "MATCH (b:%s {id: %s})\n", toLabel, cypherValue(toID))
		fmt.Fprintf(w, "MERGE (a)-[:%s]->(b);\n\n", e.Type)
	}

	return nil
}

func cypherLabels(n *Node) string {
	labels := n.Type
	if n.Type == "Resource" {
		if rc, ok := n.Properties["resource_class"].(string); ok {
			if extra := resourceClassLabel[rc]; extra != "" {
				labels += ":" + extra
			}
		}
	}
	return labels
}

func cypherMatchNode(g *GraphData, nodeID string) (string, string) {
	for i := range g.Nodes {
		if g.Nodes[i].ID == nodeID {
			return g.Nodes[i].Type, nodeID
		}
	}
	return "Node", nodeID
}

func cypherValue(v any) string {
	switch val := v.(type) {
	case string:
		return "'" + strings.ReplaceAll(val, "'", "''") + "'"
	case bool:
		if val {
			return "true"
		}
		return "false"
	case float64:
		return fmt.Sprintf("%g", val)
	case int:
		return strconv.Itoa(val)
	case []string:
		parts := make([]string, len(val))
		for i, s := range val {
			parts[i] = cypherValue(s)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case []any:
		parts := make([]string, len(val))
		for i, item := range val {
			parts[i] = cypherValue(item)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	default:
		data, _ := json.Marshal(v)
		return "'" + strings.ReplaceAll(string(data), "'", "''") + "'"
	}
}

func cypherMap(props map[string]any) string {
	var parts []string
	for k, v := range props {
		parts = append(parts, fmt.Sprintf("%s: %s", k, cypherValue(v)))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func flattenCypherProps(props map[string]any) map[string]any {
	flat := make(map[string]any)
	for k, v := range props {
		switch val := v.(type) {
		case map[string]any:
			for sk, sv := range val {
				flat[k+"."+sk] = sv
			}
		case []map[string]string:
			data, _ := json.Marshal(val)
			flat[k] = string(data)
		default:
			flat[k] = v
		}
	}
	return flat
}
