package toolmap

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

var chainTemplate = template.Must(template.New("chain").Parse(`# Generated by toolmap gap analysis — requires human review
id: {{ .ID }}
description: >
  TODO: describe the compound risk this chain detects.
  Tool prerequisite: {{ .Tool }} needs {{ .Capability }}.
controls:
  - {{ .PlaceholderControl }}
  # TODO: add member controls that check {{ .FieldPath }}
escalation_threshold: 1
compound_severity: high
preconditions: []
postconditions:
  - {{ .Capability }}
`))

type chainData struct {
	ID                 string
	Tool               string
	Capability         string
	FieldPath          string
	PlaceholderControl string
}

// GenerateSkeleton produces a chain YAML skeleton for a single gap.
func GenerateSkeleton(gap Gap) ([]byte, error) {
	data := chainData{
		ID:                 generateChainID(gap),
		Tool:               gap.Tool,
		Capability:         gap.Capability,
		FieldPath:          gap.FieldPath,
		PlaceholderControl: generatePlaceholderControlID(gap),
	}

	var buf bytes.Buffer
	if err := chainTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}
	return buf.Bytes(), nil
}

// GenerateAll writes chain skeletons for all gaps to the output directory.
// Returns the number of files written.
func GenerateAll(gaps []Gap, outputDir string) (int, error) {
	if err := os.MkdirAll(outputDir, 0o750); err != nil { //nolint:gosec // generated chain skeletons are not secrets
		return 0, fmt.Errorf("create output dir: %w", err)
	}

	written := 0
	for _, gap := range gaps {
		data, err := GenerateSkeleton(gap)
		if err != nil {
			return written, err
		}

		filename := generateChainID(gap) + ".yaml"
		path := filepath.Join(outputDir, filename)
		if err := os.WriteFile(path, data, 0o600); err != nil {
			return written, fmt.Errorf("write %s: %w", path, err)
		}
		written++
	}
	return written, nil
}

func generateChainID(gap Gap) string {
	parts := strings.Split(gap.Capability, "_")
	toolClean := strings.ReplaceAll(gap.Tool, "-", "_")
	return fmt.Sprintf("toolmap_%s_%s", toolClean, strings.Join(parts, "_"))
}

func generatePlaceholderControlID(gap Gap) string {
	// Extract the domain from the field path (e.g. "properties.identity..." → "IAM").
	parts := strings.Split(gap.FieldPath, ".")
	domain := "UNKNOWN"
	if len(parts) > 1 {
		domain = strings.ToUpper(strings.ReplaceAll(parts[1], "_", ""))
	}
	capShort := strings.ToUpper(strings.ReplaceAll(gap.Capability, "_", ""))
	// Truncate to keep the ID reasonable.
	if len(capShort) > 12 {
		capShort = capShort[:12]
	}
	return fmt.Sprintf("CTL.%s.%s.TODO001", domain, capShort)
}
