package main

// catalog_meta.go — annotation data for the curated commands-catalog.md.
// GENERATED-BOOTSTRAP then hand-maintained: each entry pairs a command
// path with its editorial group and when-to-use guidance. The Purpose
// column is NOT stored here — gencommanddocs pulls it from the live
// cobra Short so it can't drift. Add an entry when you add a leaf
// command; `make docs-commands-catalog-check` fails until you do.

// catalogGroupOrder is the display order of the curated workflow groups.
var catalogGroupOrder = []string{
	"Getting Started",
	"Control Engine (the daily loop)",
	"Workflow & CI",
	"Data & Artifacts",
	"Introspection",
	"Controls Authoring & Catalog",
	"Risk Acceptances (exempt)",
	"Snapshot Integrity & Sharing",
	"Supportability & Diagnostics",
	"Settings",
}

type catalogAnnotation struct {
	Path  string
	Group string
	When  string
}

// catalogAnnotations is ordered: groups follow catalogGroupOrder and
// commands within a group keep this slice's order (editorial, e.g.
// validate before apply before diagnose).
var catalogAnnotations = []catalogAnnotation{
	{Path: "discover", Group: "Getting Started", When: "Determining what Stave needs for your AWS services"},
	{Path: "generate", Group: "Getting Started", When: "First-time setup — scaffold a project's controls/observations layout"},
	{Path: "generate observation", Group: "Getting Started", When: "Creating a new observation snapshot to fill in"},
	{Path: "validate", Group: "Control Engine (the daily loop)", When: "Before `apply`, to catch schema/format errors early"},
	{Path: "plan", Group: "Control Engine (the daily loop)", When: "Preview what controls will evaluate before collecting data"},
	{Path: "apply", Group: "Control Engine (the daily loop)", When: "Primary evaluation — produces findings JSON (use `--dry-run` for readiness only)"},
	{Path: "diagnose", Group: "Control Engine (the daily loop)", When: "When `apply` output doesn't match expectations"},
	{Path: "diagnose explain", Group: "Control Engine (the daily loop)", When: "Turning a finding into step-by-step remediation"},
	{Path: "diagnose finding", Group: "Control Engine (the daily loop)", When: "Investigating one finding in depth"},
	{Path: "diagnose report", Group: "Control Engine (the daily loop)", When: "Human-readable diagnosis summary"},
	{Path: "diagnose trace", Group: "Control Engine (the daily loop)", When: "Debugging why a specific control did/didn't match (was the old top-level `trace`)"},
	{Path: "explain", Group: "Control Engine (the daily loop)", When: "Understanding a control before writing observations"},
	{Path: "expand", Group: "Control Engine (the daily loop)", When: "Finding all controls that match a defect pattern"},
	{Path: "check", Group: "Workflow & CI", When: "After applying a fix, to confirm it worked (was the old `verify`)"},
	{Path: "status", Group: "Workflow & CI", When: "Orientation — \"what should I do next?\""},
	{Path: "ci gate", Group: "Workflow & CI", When: "CI pipeline — fail the build on violations"},
	{Path: "ci baseline save", Group: "Workflow & CI", When: "After initial triage, to set the known state"},
	{Path: "ci baseline check", Group: "Workflow & CI", When: "CI pipeline — fail only on new violations"},
	{Path: "ci diff", Group: "Workflow & CI", When: "PR checks — what changed between two runs"},
	{Path: "ci fix", Group: "Workflow & CI", When: "Feeding a finding into an automation tool"},
	{Path: "ci fix-loop", Group: "Workflow & CI", When: "Automated remediation verification in CI"},
	{Path: "snapshot diff", Group: "Workflow & CI", When: "Spotting what changed between collections"},
	{Path: "enforce", Group: "Data & Artifacts", When: "Producing machine-readable enforcement artifacts"},
	{Path: "report", Group: "Data & Artifacts", When: "Human-readable summaries for stakeholders"},
	{Path: "compliance", Group: "Data & Artifacts", When: "Compliance posture overview"},
	{Path: "export compliance", Group: "Data & Artifacts", When: "Audit evidence for a framework"},
	{Path: "export changes", Group: "Data & Artifacts", When: "Driving automated remediation from findings"},
	{Path: "export ocsf", Group: "Data & Artifacts", When: "Feeding a SIEM/lake that speaks OCSF"},
	{Path: "export oscal", Group: "Data & Artifacts", When: "GRC tooling that consumes OSCAL"},
	{Path: "export tickets", Group: "Data & Artifacts", When: "Bulk-filing findings into a tracker"},
	{Path: "export-controls", Group: "Data & Artifacts", When: "Feeding controls to an external reasoner"},
	{Path: "export-sir", Group: "Data & Artifacts", When: "Feeding facts to external engines (Z3/Soufflé/Clingo/etc.)"},
	{Path: "bundle", Group: "Data & Artifacts", When: "Producing a tamper-evident evidence package"},
	{Path: "bundle audit", Group: "Data & Artifacts", When: "Period-end audit packaging"},
	{Path: "metrics", Group: "Data & Artifacts", When: "Exposing posture metrics to monitoring"},
	{Path: "telemetry", Group: "Data & Artifacts", When: "Streaming assessment events to a pipeline"},
	{Path: "path", Group: "Data & Artifacts", When: "Visualizing compound attack paths"},
	{Path: "graph coverage", Group: "Data & Artifacts", When: "Analyzing control coverage gaps"},
	{Path: "graph export", Group: "Data & Artifacts", When: "Importing the graph into external tooling"},
	{Path: "features", Group: "Introspection", When: "Setting expectations / scoping"},
	{Path: "score", Group: "Introspection", When: "A single headline number for a snapshot"},
	{Path: "scorecard", Group: "Introspection", When: "Posture across several frameworks at once"},
	{Path: "compare", Group: "Introspection", When: "Framework-vs-framework gap analysis"},
	{Path: "coverage", Group: "Introspection", When: "Finding which observation fields are missing"},
	{Path: "gaps", Group: "Introspection", When: "Prioritizing what to collect next"},
	{Path: "readiness", Group: "Introspection", When: "Pre-flight: will this run produce signal?"},
	{Path: "map", Group: "Introspection", When: "Mapping coverage to ATT&CK"},
	{Path: "permissions principal", Group: "Introspection", When: "\"What can this identity do?\""},
	{Path: "permissions resource", Group: "Introspection", When: "\"Who can reach this resource?\""},
	{Path: "permissions summary", Group: "Introspection", When: "Account-wide permission overview"},
	{Path: "inspect policy", Group: "Introspection", When: "Direct policy analysis without full pipeline"},
	{Path: "inspect acl", Group: "Introspection", When: "Direct ACL analysis without full pipeline"},
	{Path: "inspect exposure", Group: "Introspection", When: "Exposure analysis for custom tooling"},
	{Path: "inspect risk", Group: "Introspection", When: "Risk scoring for custom tooling"},
	{Path: "inspect compliance", Group: "Introspection", When: "Mapping controls to frameworks"},
	{Path: "inspect aliases", Group: "Introspection", When: "Discovering aliases with categories"},
	{Path: "search", Group: "Introspection", When: "\"Is there a control for X?\""},
	{Path: "bisect", Group: "Introspection", When: "Pinpointing when a regression entered"},
	{Path: "trend", Group: "Introspection", When: "Posture over time"},
	{Path: "trend forecast", Group: "Introspection", When: "Forecasting score + SLA risk"},
	{Path: "trend oscillation", Group: "Introspection", When: "Finding flapping findings"},
	{Path: "trend predict", Group: "Introspection", When: "\"When will we be compliant?\""},
	{Path: "catalog coverage", Group: "Controls Authoring & Catalog", When: "Checking catalog coverage"},
	{Path: "catalog gaps", Group: "Controls Authoring & Catalog", When: "Comparing catalog to an external checklist"},
	{Path: "catalog inspect", Group: "Controls Authoring & Catalog", When: "Deep-diving into one control's metadata"},
	{Path: "catalog stats", Group: "Controls Authoring & Catalog", When: "Aggregate catalog statistics"},
	{Path: "catalog taxonomy", Group: "Controls Authoring & Catalog", When: "Security concept categories and counts"},
	{Path: "catalog matrix", Group: "Controls Authoring & Catalog", When: "Taxonomy × service cross-product and gap analysis"},
	{Path: "controls list", Group: "Controls Authoring & Catalog", When: "Discovering available controls"},
	{Path: "controls explain", Group: "Controls Authoring & Catalog", When: "Inspecting one control's structure"},
	{Path: "controls search", Group: "Controls Authoring & Catalog", When: "Finding a control by keyword"},
	{Path: "controls quality", Group: "Controls Authoring & Catalog", When: "Catalog health review"},
	{Path: "controls aliases", Group: "Controls Authoring & Catalog", When: "Learning available shorthand predicates"},
	{Path: "controls alias-explain", Group: "Controls Authoring & Catalog", When: "Understanding what an alias resolves to"},
	{Path: "lint", Group: "Controls Authoring & Catalog", When: "Before committing controls — catches ID/metadata issues"},
	{Path: "fmt", Group: "Controls Authoring & Catalog", When: "Pre-commit / CI — canonical file format"},
	{Path: "forge new", Group: "Controls Authoring & Catalog", When: "Creating a new control interactively"},
	{Path: "forge preview", Group: "Controls Authoring & Catalog", When: "Trying a predicate before committing it"},
	{Path: "forge paths", Group: "Controls Authoring & Catalog", When: "Discovering fields to write a predicate against"},
	{Path: "forge scaffold", Group: "Controls Authoring & Catalog", When: "Bootstrapping a control's pass/fail fixtures"},
	{Path: "forge test", Group: "Controls Authoring & Catalog", When: "Verifying a control fires as intended"},
	{Path: "forge lint", Group: "Controls Authoring & Catalog", When: "Deeper control linting during authoring"},
	{Path: "forge chain", Group: "Controls Authoring & Catalog", When: "Building a compound chain"},
	{Path: "forge chain lint", Group: "Controls Authoring & Catalog", When: "Checking a chain definition"},
	{Path: "pack list", Group: "Controls Authoring & Catalog", When: "Discovering bundled control sets"},
	{Path: "pack show", Group: "Controls Authoring & Catalog", When: "Inspecting a pack before using it"},
	{Path: "packs list", Group: "Controls Authoring & Catalog", When: "Discovering bundled control sets"},
	{Path: "packs show", Group: "Controls Authoring & Catalog", When: "Inspecting a pack before using it"},
	{Path: "profile create", Group: "Controls Authoring & Catalog", When: "Starting a compliance profile"},
	{Path: "profile list", Group: "Controls Authoring & Catalog", When: "Discovering profiles"},
	{Path: "profile validate", Group: "Controls Authoring & Catalog", When: "Checking a profile before use"},
	{Path: "test", Group: "Controls Authoring & Catalog", When: "Verifying built-in controls pass their tests"},
	{Path: "exempt acknowledge", Group: "Risk Acceptances (exempt)", When: "Accepting a known risk on the record"},
	{Path: "exempt except", Group: "Risk Acceptances (exempt)", When: "Temporarily suppressing a finding"},
	{Path: "exempt asset", Group: "Risk Acceptances (exempt)", When: "Excluding an asset from scope"},
	{Path: "exempt list", Group: "Risk Acceptances (exempt)", When: "Reviewing what's accepted"},
	{Path: "exempt history", Group: "Risk Acceptances (exempt)", When: "Auditing acceptance history"},
	{Path: "exempt upcoming", Group: "Risk Acceptances (exempt)", When: "Renewal review"},
	{Path: "exempt suggest", Group: "Risk Acceptances (exempt)", When: "Triaging flapping findings"},
	{Path: "exempt remove", Group: "Risk Acceptances (exempt)", When: "Revoking an acceptance"},
	{Path: "exempt validate", Group: "Risk Acceptances (exempt)", When: "Checking the risk register is well-formed"},
	{Path: "exempt export", Group: "Risk Acceptances (exempt)", When: "Feeding the risk register to GRC"},
	{Path: "attest keygen", Group: "Snapshot Integrity & Sharing", When: "One-time key setup for attestation"},
	{Path: "attest sign", Group: "Snapshot Integrity & Sharing", When: "Producing a tamper-evident snapshot"},
	{Path: "attest verify", Group: "Snapshot Integrity & Sharing", When: "Confirming a snapshot wasn't altered"},
	{Path: "render", Group: "Snapshot Integrity & Sharing", When: "Rendering JSON data through a Go template"},
	{Path: "sanitize", Group: "Snapshot Integrity & Sharing", When: "Removing identifiers before sharing"},
	{Path: "cel eval", Group: "Snapshot Integrity & Sharing", When: "Ad-hoc CEL probing of a snapshot"},
	{Path: "contract show", Group: "Snapshot Integrity & Sharing", When: "Understanding required fields for an asset type"},
	{Path: "validate-mapping", Group: "Snapshot Integrity & Sharing", When: "Before relying on a Steampipe mapping"},
	{Path: "transform", Group: "Snapshot Integrity & Sharing", When: "Converting raw AWS CLI output to obs.v0.1 format"},
	{Path: "diff", Group: "Snapshot Integrity & Sharing", When: "What changed between two inputs"},
	{Path: "doctor", Group: "Supportability & Diagnostics", When: "First-time setup — verifies tools/paths"},
	{Path: "capabilities", Group: "Supportability & Diagnostics", When: "API introspection — what this build supports"},
	{Path: "capabilities catalog", Group: "Supportability & Diagnostics", When: "A human-readable capability list"},
	{Path: "capabilities catalog coverage", Group: "Supportability & Diagnostics", When: "Checking catalog coverage"},
	{Path: "capabilities catalog gaps", Group: "Supportability & Diagnostics", When: "Comparing catalog to an external checklist"},
	{Path: "capabilities catalog inspect", Group: "Supportability & Diagnostics", When: "Deep-diving into one control's metadata"},
	{Path: "capabilities catalog stats", Group: "Supportability & Diagnostics", When: "Aggregate catalog statistics"},
	{Path: "capabilities catalog taxonomy", Group: "Supportability & Diagnostics", When: "Security concept categories and counts"},
	{Path: "capabilities catalog matrix", Group: "Supportability & Diagnostics", When: "Taxonomy × service cross-product and gap analysis"},
	{Path: "contract", Group: "Supportability & Diagnostics", When: "Discovering input contracts"},
	{Path: "schemas", Group: "Supportability & Diagnostics", When: "Reference during schema development"},
	{Path: "version", Group: "Supportability & Diagnostics", When: "Debugging build provenance"},
	{Path: "config show", Group: "Settings", When: "Debugging config resolution"},
	{Path: "config get", Group: "Settings", When: "Scripting / automation"},
	{Path: "config set", Group: "Settings", When: "Customizing project defaults"},
	{Path: "config delete", Group: "Settings", When: "Resetting a value"},
	{Path: "config explain", Group: "Settings", When: "Understanding precedence (env/file/default)"},
	{Path: "config context create", Group: "Settings", When: "Multi-project setups"},
	{Path: "config context use", Group: "Settings", When: "Switching between projects"},
	{Path: "config context show", Group: "Settings", When: "Checking the active context"},
	{Path: "config context list", Group: "Settings", When: "Seeing all configured contexts"},
	{Path: "config context delete", Group: "Settings", When: "Removing a stale context"},
	{Path: "config env list", Group: "Settings", When: "Discovering env-based configuration"},
	{Path: "alias set", Group: "Settings", When: "Developer convenience shortcuts"},
	{Path: "alias list", Group: "Settings", When: "Reviewing configured shortcuts"},
	{Path: "alias delete", Group: "Settings", When: "Removing a stale shortcut"},
	{Path: "completion", Group: "Settings", When: "Tab-completion setup for bash/zsh/fish/ps"},
	{Path: "fingerprint explain", Group: "Introspection", When: "Diagnosing or auditing the policy fingerprint"},
	{Path: "prove", Group: "Introspection", When: "Formal verification of IAM policies and control invariants via Z3 SMT"},
	{Path: "recommend", Group: "Workflow", When: "Discovering which assessment template fits a snapshot"},
	{Path: "template init", Group: "Workflow", When: "Instantiating an assessment template with parameters"},
	{Path: "template new", Group: "Workflow", When: "Scaffolding a custom template for authoring"},
	{Path: "template verify", Group: "Workflow", When: "Verifying a template's fixture produces expected findings"},
	{Path: "template eject", Group: "Workflow", When: "Forking a template for local customization"},
}
