// Command gencommanddocs generates the CLI command reference from the
// live cobra command tree — the single source of truth is the binary's
// own command wiring, so the doc cannot drift from the actual commands.
//
// Usage:
//
//	go run ./internal/tools/gencommanddocs           # write docs/command-reference.md
//	go run ./internal/tools/gencommanddocs -check    # exit 1 if the reference is stale
//	go run ./internal/tools/gencommanddocs -out path # custom output path
//
// Descriptions come from each command's cobra `Short`, which is already
// maintained per-command. Un-derivable curated columns (Input / Output /
// "when to use") are intentionally not emitted — keeping the generated
// doc to what the tree actually knows is what makes it drift-proof.
package main

import (
	"bytes"
	"cmp"
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/spf13/cobra"

	"github.com/sufield/stave/cmd"
)

func main() {
	outPath := flag.String("out", "docs/command-reference.md", "output file for the generated command reference")
	check := flag.Bool("check", false, "check mode: exit 1 if the command reference is stale")
	catalog := flag.String("catalog", "", "generate the curated when-to-use catalog (from catalog_meta.go annotations) to this path")
	catalogCheck := flag.String("catalog-check", "", "verify the curated catalog at this path is in sync with the annotations + binary")
	flag.Parse()

	app, err := cmd.NewApp()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: wire CLI: %v\n", err)
		os.Exit(1)
	}

	// Curated-catalog modes: generate or check commands-catalog.md from the
	// annotation data + the live cobra tree.
	if *catalog != "" || *catalogCheck != "" {
		buf, err := renderCatalog(app.Root)
		if err != nil {
			fmt.Fprintf(os.Stderr, "%v\n", err)
			os.Exit(1)
		}
		if *catalogCheck != "" {
			existing, readErr := os.ReadFile(*catalogCheck)
			if readErr != nil {
				fmt.Fprintf(os.Stderr, "error: %v\n", readErr)
				os.Exit(1)
			}
			if !bytes.Equal(existing, buf.Bytes()) {
				fmt.Fprintf(os.Stderr, "%s is stale. Run: make docs-commands-catalog\n", *catalogCheck)
				os.Exit(1)
			}
			fmt.Printf("%s: in sync\n", *catalogCheck)
			return
		}
		if err := os.WriteFile(*catalog, buf.Bytes(), 0o600); err != nil {
			fmt.Fprintf(os.Stderr, "error: write %s: %v\n", *catalog, err)
			os.Exit(1)
		}
		fmt.Printf("wrote %s (%d annotated commands)\n", *catalog, len(catalogAnnotations))
		return
	}

	buf, total := render(app.Root)

	if *check {
		existing, readErr := os.ReadFile(*outPath)
		if readErr != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", readErr)
			os.Exit(1)
		}
		if !bytes.Equal(existing, buf.Bytes()) {
			fmt.Fprintf(os.Stderr, "%s is stale. Run: make docs-commands\n", *outPath)
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(*outPath, buf.Bytes(), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "error: write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d commands)\n", *outPath, total)
}

// renderCatalog generates the curated when-to-use catalog
// (commands-catalog.md) from the annotation data in catalog_meta.go
// joined with the live cobra tree. The Purpose column comes from each
// command's cobra Short — never stored in the annotations — so it cannot
// drift. Returns an error (without writing) when the annotations and the
// binary disagree, enforcing the same invariants that let the catalog rot:
//   - no phantom: every annotated path must be a real command.
//   - no missing leaf: every leaf command must be annotated. Bare
//     parent/group commands may be annotated but are not required.
func renderCatalog(root *cobra.Command) (*bytes.Buffer, error) {
	all, leaves := collectPaths(root)
	short := shortByPath(root)

	annotated := map[string]bool{}
	var phantom []string
	for _, a := range catalogAnnotations {
		annotated[a.Path] = true
		if !all[a.Path] {
			phantom = append(phantom, a.Path)
		}
	}
	var missing []string
	for c := range leaves {
		if !annotated[c] {
			missing = append(missing, c)
		}
	}
	slices.Sort(phantom)
	slices.Sort(missing)
	if len(phantom) > 0 || len(missing) > 0 {
		var b strings.Builder
		b.WriteString("catalog annotations are out of sync with the binary:\n")
		for _, c := range phantom {
			fmt.Fprintf(&b, "  phantom (remove from catalog_meta.go): %s\n", c)
		}
		for _, c := range missing {
			fmt.Fprintf(&b, "  missing  (add to catalog_meta.go):       %s\n", c)
		}
		return nil, fmt.Errorf("%s", b.String())
	}

	var buf bytes.Buffer
	buf.WriteString("# Stave Commands — When to Reach for Each\n\n")
	buf.WriteString("<!-- GENERATED by internal/tools/gencommanddocs from\n")
	buf.WriteString("     catalog_meta.go (annotations) + the live cobra tree. DO NOT EDIT.\n")
	buf.WriteString("     Regenerate with `make docs-commands-catalog`. Edit the when-to-use\n")
	buf.WriteString("     text or grouping in internal/tools/gencommanddocs/catalog_meta.go. -->\n\n")
	buf.WriteString("Authoritative command inventory: `stave/docs/command-reference.md`\n")
	buf.WriteString("(also generated). This is the curated *when-to-use* companion. Purpose\n")
	buf.WriteString("comes from each command's `--help` summary; run `stave <command> --help`\n")
	buf.WriteString("for full flags and exit codes.\n")

	for _, group := range catalogGroupOrder {
		rows := annotationsForGroup(group)
		if len(rows) == 0 {
			continue
		}
		fmt.Fprintf(&buf, "\n## %s\n\n", group)
		buf.WriteString("| Command | Purpose | When to use |\n|---|---|---|\n")
		for _, a := range rows {
			fmt.Fprintf(&buf, "| `%s` | %s | %s |\n",
				a.Path, escapePipes(short[a.Path]), escapePipes(a.When))
		}
	}

	return &buf, nil
}

// annotationsForGroup returns the annotations in the given group,
// preserving catalogAnnotations slice order (editorial ordering).
func annotationsForGroup(group string) []catalogAnnotation {
	var out []catalogAnnotation
	for _, a := range catalogAnnotations {
		if a.Group == group {
			out = append(out, a)
		}
	}
	return out
}

// shortByPath maps every command path to its cobra Short.
func shortByPath(root *cobra.Command) map[string]string {
	m := map[string]string{}
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		for _, sub := range c.Commands() {
			if skip(sub) {
				continue
			}
			m[commandPath(sub)] = sub.Short
			walk(sub)
		}
	}
	walk(root)
	return m
}

// collectPaths walks the tree and returns the set of all command paths
// and the subset that are leaves (no non-skipped subcommands).
func collectPaths(root *cobra.Command) (all, leaves map[string]bool) {
	all, leaves = map[string]bool{}, map[string]bool{}
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		for _, sub := range c.Commands() {
			if skip(sub) {
				continue
			}
			p := commandPath(sub)
			all[p] = true
			hasChild := false
			for _, g := range sub.Commands() {
				if !skip(g) {
					hasChild = true
					break
				}
			}
			if !hasChild {
				leaves[p] = true
			}
			walk(sub)
		}
	}
	walk(root)
	return all, leaves
}

// entry is one command row: its full invocation path and cobra Short.
type entry struct {
	path  string
	short string
}

// additionalGroupID is the synthetic bucket for top-level commands that
// carry no cobra GroupID (cobra renders them under "Additional Commands").
const additionalGroupID = "__additional__"

// render walks the tree and produces the markdown reference plus the
// total command count. Output is deterministic: groups follow the root's
// declared group order (then the additional bucket), and commands within
// a group are sorted by full path.
func render(root *cobra.Command) (*bytes.Buffer, int) {
	// Collect entries per top-level group.
	byGroup := map[string][]entry{}
	total := 0
	for _, top := range root.Commands() {
		if skip(top) {
			continue
		}
		gid := top.GroupID
		if gid == "" {
			gid = additionalGroupID
		}
		var collect func(c *cobra.Command)
		collect = func(c *cobra.Command) {
			byGroup[gid] = append(byGroup[gid], entry{path: commandPath(c), short: c.Short})
			total++
			for _, sub := range c.Commands() {
				if skip(sub) {
					continue
				}
				collect(sub)
			}
		}
		collect(top)
	}

	// Group display order: declared groups first, then the additional bucket.
	type groupHeader struct {
		id    string
		title string
	}
	order := []groupHeader{}
	for _, g := range root.Groups() {
		order = append(order, groupHeader{id: g.ID, title: g.Title})
	}
	order = append(order, groupHeader{id: additionalGroupID, title: "Additional Commands"})

	groupCount := 0
	for _, g := range order {
		if len(byGroup[g.id]) > 0 {
			groupCount++
		}
	}

	var buf bytes.Buffer
	buf.WriteString("# Command Reference\n\n")
	buf.WriteString("<!-- GENERATED by internal/tools/gencommanddocs — DO NOT EDIT.\n")
	buf.WriteString("     Regenerate with `make docs-commands`. Source of truth: the\n")
	buf.WriteString("     cobra command tree in the stave binary (prod edition). -->\n\n")
	buf.WriteString("All commands ship in the standard `stave` binary. No build tags are\n")
	buf.WriteString("required. Descriptions are each command's one-line summary; run\n")
	buf.WriteString("`stave <command> --help` for full usage, flags, and exit codes.\n\n")
	fmt.Fprintf(&buf, "_%d commands across %d groups._\n", total, groupCount)

	for _, g := range order {
		entries := byGroup[g.id]
		if len(entries) == 0 {
			continue
		}
		slices.SortFunc(entries, func(a, b entry) int { return cmp.Compare(a.path, b.path) })
		fmt.Fprintf(&buf, "\n## %s\n\n", g.title)
		buf.WriteString("| Command | Description |\n|---|---|\n")
		for _, e := range entries {
			fmt.Fprintf(&buf, "| `%s` | %s |\n", e.path, escapePipes(e.short))
		}
	}

	return &buf, total
}

// commandPath returns the invocation path without the root name, e.g.
// "ci baseline check".
func commandPath(c *cobra.Command) string {
	full := c.CommandPath() // "stave ci baseline check"
	return strings.TrimPrefix(full, c.Root().Name()+" ")
}

// skip drops hidden commands and cobra's auto-generated help command.
func skip(c *cobra.Command) bool {
	return c.Hidden || c.Name() == "help"
}

func escapePipes(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
