// Command gencommanddocs generates the CLI command reference from the
// live cobra command tree — the single source of truth is the binary's
// own command wiring, so the doc cannot drift from the actual commands.
//
// Usage:
//
//	go run ./internal/tools/gencommanddocs           # write docs/command-reference.md
//	go run ./internal/tools/gencommanddocs -check    # exit 1 if the reference is stale
//	go run ./internal/tools/gencommanddocs -out path # custom output path
//
// Descriptions come from each command's cobra `Short`, which is already
// maintained per-command. Un-derivable curated columns (Input / Output /
// "when to use") are intentionally not emitted — keeping the generated
// doc to what the tree actually knows is what makes it drift-proof.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/spf13/cobra"

	"github.com/sufield/stave/cmd"
)

func main() {
	outPath := flag.String("out", "docs/command-reference.md", "output file")
	check := flag.Bool("check", false, "check mode: exit 1 if output is stale")
	flag.Parse()

	app, err := cmd.NewApp()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: wire CLI: %v\n", err)
		os.Exit(1)
	}

	buf, total := render(app.Root)

	if *check {
		existing, readErr := os.ReadFile(*outPath)
		if readErr != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", readErr)
			os.Exit(1)
		}
		if !bytes.Equal(existing, buf.Bytes()) {
			fmt.Fprintf(os.Stderr, "%s is stale. Run: make docs-commands\n", *outPath)
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(*outPath, buf.Bytes(), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "error: write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d commands)\n", *outPath, total)
}

// entry is one command row: its full invocation path and cobra Short.
type entry struct {
	path  string
	short string
}

// additionalGroupID is the synthetic bucket for top-level commands that
// carry no cobra GroupID (cobra renders them under "Additional Commands").
const additionalGroupID = "__additional__"

// render walks the tree and produces the markdown reference plus the
// total command count. Output is deterministic: groups follow the root's
// declared group order (then the additional bucket), and commands within
// a group are sorted by full path.
func render(root *cobra.Command) (*bytes.Buffer, int) {
	// Collect entries per top-level group.
	byGroup := map[string][]entry{}
	total := 0
	for _, top := range root.Commands() {
		if skip(top) {
			continue
		}
		gid := top.GroupID
		if gid == "" {
			gid = additionalGroupID
		}
		var collect func(c *cobra.Command)
		collect = func(c *cobra.Command) {
			byGroup[gid] = append(byGroup[gid], entry{path: commandPath(c), short: c.Short})
			total++
			for _, sub := range c.Commands() {
				if skip(sub) {
					continue
				}
				collect(sub)
			}
		}
		collect(top)
	}

	// Group display order: declared groups first, then the additional bucket.
	type groupHeader struct {
		id    string
		title string
	}
	order := []groupHeader{}
	for _, g := range root.Groups() {
		order = append(order, groupHeader{id: g.ID, title: g.Title})
	}
	order = append(order, groupHeader{id: additionalGroupID, title: "Additional Commands"})

	groupCount := 0
	for _, g := range order {
		if len(byGroup[g.id]) > 0 {
			groupCount++
		}
	}

	var buf bytes.Buffer
	buf.WriteString("# Command Reference\n\n")
	buf.WriteString("<!-- GENERATED by internal/tools/gencommanddocs — DO NOT EDIT.\n")
	buf.WriteString("     Regenerate with `make docs-commands`. Source of truth: the\n")
	buf.WriteString("     cobra command tree in the stave binary (prod edition). -->\n\n")
	buf.WriteString("All commands ship in the standard `stave` binary. No build tags are\n")
	buf.WriteString("required. Descriptions are each command's one-line summary; run\n")
	buf.WriteString("`stave <command> --help` for full usage, flags, and exit codes.\n\n")
	fmt.Fprintf(&buf, "_%d commands across %d groups._\n", total, groupCount)

	for _, g := range order {
		entries := byGroup[g.id]
		if len(entries) == 0 {
			continue
		}
		slices.SortFunc(entries, func(a, b entry) int { return strings.Compare(a.path, b.path) })
		fmt.Fprintf(&buf, "\n## %s\n\n", g.title)
		buf.WriteString("| Command | Description |\n|---|---|\n")
		for _, e := range entries {
			fmt.Fprintf(&buf, "| `%s` | %s |\n", e.path, escapePipes(e.short))
		}
	}

	return &buf, total
}

// commandPath returns the invocation path without the root name, e.g.
// "ci baseline check".
func commandPath(c *cobra.Command) string {
	full := c.CommandPath()                  // "stave ci baseline check"
	return strings.TrimPrefix(full, c.Root().Name()+" ")
}

// skip drops hidden commands and cobra's auto-generated help command.
func skip(c *cobra.Command) bool {
	return c.Hidden || c.Name() == "help"
}

func escapePipes(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
